import React from 'react';

declare global {
  interface AIStudio {
    hasSelectedApiKey: () => Promise<boolean>;
    openSelectKey: () => Promise<void>;
  }

  interface Window {
    webkitAudioContext: typeof AudioContext;
    aistudio?: AIStudio;
  }
}

export type Platform = 'Instagram' | 'TikTok' | 'X' | 'Threads' | 'YouTube' | 'LinkedIn' | 'Facebook' | 'Pinterest' | 'My Page';

export type MessageType = 'DM' | 'Comment';
// Business categories: Lead, Support, Opportunity, General
// Creator categories: Fan Message, Question, Collab Request, Feedback, General
export type MessageCategory = 'Lead' | 'Support' | 'Opportunity' | 'General' | 'Fan Message' | 'Question' | 'Collab Request' | 'Feedback';

export interface Message {
  id: string; 
  platform: Platform;
  type: MessageType;
  user: {
    name: string;
    avatar: string;
  };
  content: string;
  timestamp: string; 
  assigneeId?: string; 
  sentiment?: 'Positive' | 'Neutral' | 'Negative';
  isArchived?: boolean;
  isFlagged?: boolean;
  isFavorite?: boolean;
  clientId?: string; 
  category?: MessageCategory;
}

export interface AnalyticsData {
  responseRate: { name: string; value: number }[];
  followerGrowth: { name: string; value: number }[];
  totalReplies: number;
  newFollowers: number;
  engagementIncrease: number;
  sentiment: { name: string; value: number }[];
  topTopics: string[];
  suggestedFaqs: string[];
  engagementInsights: {
    icon: 'idea' | 'topic' | 'question';
    title: string;
    description: string;
  }[];
}

export type Page = 'dashboard' | 'analytics' | 'settings' | 'compose' | 'calendar' | 'team' | 'opportunities' | 'profile' | 'about' | 'contact' | 'pricing' | 'clients' | 'faq' | 'terms' | 'privacy' | 'dataDeletion' | 'admin' | 'automation' | 'approvals' | 'bio' | 'strategy' | 'autopilot' | 'ads' | 'mediaLibrary' | 'onlyfansStudio' | 'emailCenter' | 'premiumStudioUpgrade' | 'fanHub';

export interface Settings {
    autoReply: boolean;
    autoRespond: boolean;
    safeMode: boolean;
    highQuality: boolean; 
    tone: {
      formality: number;
      humor: number;
      empathy: number;
      spiciness?: number;
      emojiLevel?: number;
      profanity?: number;
    };
    voiceMode: boolean;
    prioritizedKeywords: string;
    ignoredKeywords: string;
    connectedAccounts: Record<Platform, boolean>;
    monetizedModeEnabled?: boolean;
    monetizedOnboarding?: {
      postingFrequency?: string;
      contentHelp?: string[];
      biggestChallenge?: string;
      monthlyGoal?: string;
    };
    monetizedPlatforms?: string[];
    enableAdminDashboardV2?: boolean;
    creatorPersonality?: string; // Personality description/brand for AI caption generation
    favoriteHashtags?: string; // Comma-separated favorite hashtags
}

export interface CaptionResult {
    caption: string;
    hashtags: string[];
}

export type Role = 'Admin' | 'Member';

export interface TeamMember {
    id: string; 
    name: string;
    email: string;
    avatar: string;
    role: Role;
    assignedClientIds?: string[];
}

export interface Opportunity {
    id: string;
    type: 'Trending Hashtag' | 'Viral Audio' | 'Popular Topic' | 'Collaboration Opportunity' | 'Content Gap';
    title: string;
    description: string;
    platform: Platform;
    engagementPotential?: number; // 1-10 scale
    trendingVelocity?: 'Rising' | 'Peak' | 'Declining';
    relatedHashtags?: string[];
    bestPractices?: string;
    saved?: boolean;
    createdAt?: string;
}

export interface ChatMessage {
  role: 'user' | 'bot';
  content: string;
}

export interface SocialStats {
    followers: number;
    following: number;
}

export type SocialStatsByPlatform = Record<Platform, SocialStats> & {
  totalFollowers?: number;
  totalReach?: number;
};

export interface BioLink {
    id: string;
    title: string;
    url: string;
    isActive: boolean;
    clicks: number;
    thumbnail?: string;
    icon?: string;
}

export interface SocialBioLink {
    id: string;
    platform: Platform;
    url: string;
    username: string;
    isActive: boolean;
    clicks: number;
    autoGenerated: boolean;
}

export interface EmailCaptureConfig {
    enabled: boolean;
    title: string;
    placeholder: string;
    buttonText: string;
    successMessage: string;
    formBackgroundColor?: string;
    titleColor?: string;
    inputBackgroundColor?: string;
    inputTextColor?: string;
    buttonBackgroundColor?: string;
    buttonTextColor?: string;
}

export interface BioPageConfig {
    username: string;
    displayName: string;
    verified: boolean;
    bio: string;
    avatar: string;
    totalFollowers?: number;
    socialLinks: SocialBioLink[];
    customLinks: BioLink[];
    links?: BioLink[]; // Legacy support
    teaserImages?: string[]; // Array of image URLs for teaser pics
    theme: {
        backgroundColor: string; // legacy field for backward compatibility
        pageBackgroundColor?: string;
        cardBackgroundColor?: string;
        buttonColor: string;
        /**
         * Legacy text color field used historically for both page text and button text.
         * Prefer `pageTextColor` + `buttonTextColor` going forward.
         */
        textColor: string;
        /** Text color used for page/card text (name, username, bio, headings). */
        pageTextColor?: string;
        /** Text color used on buttons (link labels). */
        buttonTextColor?: string;
        buttonStyle: 'rounded' | 'square' | 'pill';
    };
    emailCapture?: EmailCaptureConfig;
}

/** Button style for storefront theme */
export type StorefrontButtonStyle = 'solid' | 'outline' | 'pill';

/** Monetization settings (non-explicit, IG-like) */
export interface CreatorMonetization {
    monthlyPrice?: number;       // cents or display value; platform interprets
    currency?: 'usd';
    lockedDefaultPrice?: number; // cents
    tipsEnabled?: boolean;
    chatEnabled?: boolean;
    videoEnabled?: boolean;      // Live video chat enabled
    freeAccessEnabled?: boolean; // Allow fans to join for free (no subscription required)
}

/** Social link configuration for a single platform */
export interface SocialLinkConfig {
    url: string;
    show: boolean;
}

/** All social links for a creator's storefront */
export interface CustomSocialLink {
    name: string;
    url: string;
    show: boolean;
    icon?: string;
}

export interface StorefrontSocialLinks {
    instagram?: SocialLinkConfig;
    facebook?: SocialLinkConfig;
    x?: SocialLinkConfig;
    tiktok?: SocialLinkConfig;
    youtube?: SocialLinkConfig;
    custom?: CustomSocialLink[];
}

/** Landing page content sections (editable by creator) */
export interface StorefrontLandingContent {
    perksTitle?: string;        // "Why This Exists" section title
    perksText?: string;         // Main text for perks section
    perksList?: string[];       // Bullet points list
    previewTitle?: string;      // "What You Get" section title
    previewText?: string;       // Main text for preview section
    previewList?: string[];     // Features list
    energyTitle?: string;       // "The Energy" testimonial section title
    energyLines?: string[];     // Array of energy/vibe lines
    boundaryTitle?: string;     // "The Boundary" FAQ section title
    boundaryText?: string;      // Boundary/rules text
}

/** Legal pages configuration */
export interface StorefrontLegal {
    termsText?: string;
    termsLastUpdated?: string;  // ISO date string
    privacyText?: string;
    privacyLastUpdated?: string; // ISO date string
}

/** Text styling for storefront customization */
export interface TextStyle {
    fontSize?: 'xs' | 'sm' | 'base' | 'lg' | 'xl' | '2xl' | '3xl';
    color?: string; // hex color
    fontFamily?: string; // font family name
}

/** Fan Hub My Page / storefront settings persisted at creators/{creatorId} */
export interface CreatorStorefrontSettings {
    handle: string; // unique, lowercase, 3-20 chars, alphanumeric + underscore; URL /{handle}
    displayName?: string;
    bio?: string;
    avatar?: string; // image URL - shown on feed posts (profile pic)
    /** CSS object-position for avatar when shown in circular crop (e.g. full-background hero). E.g. `40% 20%`. */
    avatarObjectPosition?: string;
    logo?: string;   // image URL - shown in header (like Stormij XO logo)
    /** When false, hide display name from landing hero (still shown in header and feed) */
    showDisplayNameOnLanding?: boolean;

    // Hero Section
    heroImage?: string;         // Legacy: single hero image URL (used if heroMedia is empty)
    /** Multiple hero images with optional size. fullBackground = one image as section background. */
    heroMedia?: {
        url: string;
        size?: 'small' | 'medium' | 'large' | 'fullBackground';
        /** When size is fullBackground: which part of the image is visible (CSS background-position, e.g. `45% 30%`). */
        backgroundPosition?: string;
        /** For grid hero images: focal point (CSS object-position, e.g. `50% 25%`). */
        objectPosition?: string;
        /** fullBackground only: avatar overlay horizontal offset (CSS length, e.g. `1rem` or `24px`). */
        landingAvatarLeft?: string;
        /** fullBackground only: avatar offset from section bottom (CSS length, often negative e.g. `-48px`). */
        landingAvatarBottom?: string;
    }[];
    heroTagline?: string;       // Short tagline under display name
    heroPromise?: string;       // "Your access to..." promise text
    heroSubline?: string;       // Extra line after promise text on landing hero
    
    // Text Styling (font size & color per field)
    textStyles?: {
        displayName?: TextStyle;
        bio?: TextStyle;
        heroTagline?: TextStyle;
        heroPromise?: TextStyle;
        heroSubline?: TextStyle;
        perksTitle?: TextStyle;
        perksText?: TextStyle;
        previewTitle?: TextStyle;
        previewText?: TextStyle;
        energyTitle?: TextStyle;
        boundaryTitle?: TextStyle;
        boundaryText?: TextStyle;
    };
    
    // Social Links
    socialLinks?: StorefrontSocialLinks;
    
    // Landing Page Content
    landingContent?: StorefrontLandingContent;
    
    // Legal
    legal?: StorefrontLegal;
    
    theme?: {
        primary: string;
        background: string;
        text?: string;   // hex, default from background contrast
        textMuted?: string; // hex, muted/secondary text color
        border?: string;    // hex, border color for cards/sections
        accentHover?: string; // hex, hover state for accent/primary
        buttonStyle?: StorefrontButtonStyle; // 'solid' | 'outline' | 'pill'
        /** Global font family for storefront (e.g. "Inter, sans-serif") */
        fontFamily?: string;
        /** Id of a preset (e.g. "default" | "stormij" | "ocean") for quick apply */
        presetId?: string;
    };
    /** Hero section layout on landing: default (image + text stack) | centered (compact) | split (image left, text right) */
    heroLayout?: 'default' | 'centered' | 'split' | 'splitRight';
    sections?: {
        feed: boolean;
        treats: boolean;
        tip: boolean;
        messages: boolean;
        about?: boolean;
    };
    /** Order of section keys for tab bar (e.g. ['feed','treats','messages','about']) */
    sectionsOrder?: string[];
    spicyMode?: boolean; // 18+ gate + policy text on storefront
    rules?: {
        boundariesText?: string; // About/Boundaries block (markdown or plain)
    };
    monetization?: CreatorMonetization;
    onboardingStatus?: string;
    updatedAt?: string;  // ISO
}

/** Treats store product type (creator-defined treat types in Fan Hub) */
export type TreatProductType =
    | 'tip'
    | 'unlock_media'
    | 'bundle'
    | 'chat_session'
    | 'voice_note_30s'
    | 'voice_note_60s'
    | 'private_video_reply'
    | 'birthday_message'
    | 'overthinking_response'
    | 'random_checkin'
    | 'live_chat_5m'
    | 'live_chat_15m'
    | 'live_chat_30m'
    | 'live_chat_45m'
    | 'live_chat_60m'
    | 'live_chat_1h'
    | 'live_video_5m'
    | 'live_video_10m'
    | 'live_video_15m'
    | 'live_video_30m'
    | 'live_video_45m'
    | 'live_video_60m'
    | 'custom';

/** Single product in the treats store (Firestore: products/{productId}) */
export interface TreatProduct {
    id: string;
    creatorId: string;
    type: TreatProductType;
    title: string;
    description?: string;
    /** Price in cents (e.g. 499 = $4.99) */
    priceCents: number;
    /** For unlock_media: media URL or storage path */
    mediaUrl?: string;
    /** Card thumbnail/preview image URL */
    imageUrl?: string;
    archived: boolean;
    /** When false, product is hidden from storefront (creator toggle) */
    visible: boolean;
    sortOrder?: number;
    /** For live_video types: duration in minutes */
    durationMinutes?: number;
    /** Quantity limit (sold out when soldCount >= quantityLimit) */
    quantityLimit?: number;
    /** Number sold */
    soldCount?: number;
    createdAt: Date | string;  // ISO or Date
    updatedAt: Date | string;  // ISO or Date
}

/** Live Video Chat Session Status */
export type LiveVideoChatStatus = 
    | 'pending'      // Fan requested, waiting for creator
    | 'accepted'     // Creator accepted, room ready
    | 'active'       // Both parties in call
    | 'completed'    // Session ended normally
    | 'declined'     // Creator declined
    | 'expired'      // Request timed out
    | 'cancelled';   // Fan cancelled

/** Live Video Chat Session (Firestore: creators/{creatorId}/liveVideoChats/{sessionId}) */
export interface LiveVideoChatSession {
    id: string;
    creatorId: string;
    fanId: string;
    fanEmail?: string;
    fanDisplayName?: string;
    /** Product ID that was purchased */
    productId: string;
    /** Duration purchased in minutes */
    durationMinutes: number;
    /** Actual minutes used */
    minutesUsed: number;
    /** Amount paid in cents */
    amountPaidCents: number;
    /** Creator earnings after commission */
    creatorEarningsCents: number;
    status: LiveVideoChatStatus;
    /** Daily.co room URL */
    roomUrl?: string;
    /** Daily.co room name */
    roomName?: string;
    /** Optional note from fan when requesting */
    fanNote?: string;
    requestedAt: string;  // ISO
    acceptedAt?: string;  // ISO
    startedAt?: string;   // ISO
    endedAt?: string;     // ISO
    /** Scheduled for later (ISO timestamp) */
    scheduledFor?: string;
}

/** Fan entitlement per creator: subscription + unlocked product ids (Firestore: creatorEntitlements/{creatorId}/grants/{fanId}) */
export interface FanEntitlementGrant {
    subscription: boolean;
    unlockedProductIds: string[];
    updatedAt: string;  // ISO
}

/** Fan–creator DM thread (Firestore: fanDmThreads/{threadId}); threadId = [creatorId, fanId].sort().join('_') */
export interface FanDmThread {
    id: string;
    creatorId: string;
    fanId: string;
    lastMessageAt: string;  // ISO
    lastMessagePreview?: string;
    createdAt: string;
    updatedAt: string;
    /** For list display: other party display name/avatar (set by API) */
    otherPartyDisplayName?: string;
    otherPartyAvatar?: string;
}

/** Single message in a fan–creator thread (Firestore: fanDmThreads/{threadId}/messages/{messageId}) */
export interface FanDmMessage {
    id: string;
    threadId: string;
    senderId: string;   // creatorId or fanId
    content: string;
    createdAt: string;  // ISO
    reported?: boolean;
    reportId?: string;
}

/** Report for admin review (Firestore: reports/{reportId}) */
export interface FanDmReport {
    id: string;
    creatorId: string;
    fanId: string;
    threadId: string;
    messageId: string;
    reporterId: string;  // who reported (creator or fan)
    reason: string;
    status: 'pending' | 'reviewed' | 'dismissed';
    createdAt: string;
    reviewedAt?: string;
    reviewedBy?: string;
}

export type Plan = 'Free' | 'Caption' | 'Pro' | 'Elite' | 'Agency' | 'Growth' | 'Starter' | 'OnlyFansStudio';

export interface Client {
  id: string;
  name: string;
  avatar: string;
  plan: Plan;
  notifications: {
    newMessages: boolean;
    weeklySummary: boolean;
    trendAlerts: boolean;
  };
  monthlyCaptionGenerationsUsed: number;
  monthlyImageGenerationsUsed: number;
  monthlyVideoGenerationsUsed: number;
  mediaLibrary: MediaItem[];
  storageUsed: number; 
  storageLimit: number; 
  settings: Settings;
  approvalLink?: string; 
  socialStats?: SocialStatsByPlatform;
  bioPage?: BioPageConfig;
  referralCode?: string;
  referralStats?: ReferralStats;
  /** Admin-granted rewards history (manual adjustments via Admin Dashboard). */
  manualReferralRewards?: Array<{
    rewardType: 'extra_generations' | 'strategy_generations' | 'free_month' | 'storage_boost' | string;
    rewardAmount: number;
    grantedAt: string;
    grantedBy: string;
    reason?: string;
  }>;
}

export interface MediaItem {
  id: string;
  url: string; 
  name: string;
  size: number; 
  type: 'image' | 'video';
  uploadedAt: string;
}

export interface MediaLibraryItem {
  id: string;
  userId: string;
  url: string;
  name: string;
  type: 'image' | 'video' | 'audio';
  mimeType: string;
  size?: number;
  uploadedAt: string;
  usedInPosts?: string[]; // Array of post IDs where this media was used
  tags?: string[];
  duration?: number; // Duration in seconds for audio/video
  folderId?: string; // Folder ID - defaults to 'general' if not set
}

export interface MediaFolder {
  id: string;
  userId: string;
  name: string;
  createdAt: string;
  itemCount?: number; // Optional: count of items in folder (can be computed)
}

export interface HashtagSet {
    id: string;
    name: string;
    tags: string[];
}

export type UserType = 'Creator' | 'Business';

export interface Referral {
  id: string;
  referrerId: string;
  refereeId: string;
  referralCode: string;
  createdAt: string;
  rewardStatus: 'pending' | 'claimed' | 'expired';
  rewardType?: 'free_month' | 'extra_generations' | 'storage_boost';
  rewardAmount?: number;
  claimedAt?: string;
}

export interface ReferralReward {
  milestone: number;
  type: 'free_month' | 'extra_generations' | 'storage_boost';
  amount: number;
  description: string;
  isEarned: boolean;
  isClaimed: boolean;
}

export interface ReferralStats {
  totalReferrals: number;
  activeReferrals: number;
  rewardsEarned: number;
  referralCode: string;
}

export interface User {
  id: string;
  name: string;
  email: string;
  avatar: string;
  bio: string;
  plan: Plan | null; // null when payment is pending
  role: 'Admin' | 'User';
  signupDate: string;
  userType?: UserType;
  businessName?: string;
  businessType?: string;
  businessGoal?: string;
  niche?: string;
  audience?: string;
  hasCompletedOnboarding?: boolean;
  hasAutopilot?: boolean; 
  notifications: {
    newMessages: boolean;
    weeklySummary: boolean;
    trendAlerts: boolean;
  };
  monthlyCaptionGenerationsUsed: number;
  monthlyImageGenerationsUsed: number;
  monthlyVideoGenerationsUsed: number;
  monthlyAdGenerationsUsed?: number;
  monthlyVideoAdGenerationsUsed?: number;
  monthlyRepliesUsed?: number; // Track AI reply usage for Free plan limit
  /** Compose advanced features usage (resets monthly; enforced server-side) */
  monthlyContentGapsUsed?: number;
  monthlyPredictionsUsed?: number;
  monthlyRepurposesUsed?: number;
  /** Month key (YYYY-MM) used to reset compose advanced usage counters */
  composeInsightsUsageMonth?: string;
  storageUsed: number; 
  storageLimit: number; 
  mediaLibrary: MediaItem[];
  settings: Settings;
  hashtagSets?: HashtagSet[];
  socialStats?: SocialStatsByPlatform;
  goals?: {
    followerGoal?: number; // For Creators: followers goal, For Business: reach goal
    monthlyPostsGoal?: number;
    monthlyLeadsGoal?: number; // Business-specific: target leads per month
  };
  bioPage?: BioPageConfig;
  socialAccounts?: SocialAccount[]; // OAuth-connected social media accounts
  stripeCustomerId?: string; // Stripe Customer ID (set by webhook)
  stripeSubscriptionId?: string; // Stripe Subscription ID (set by webhook)
  subscriptionEndDate?: string; // ISO timestamp when subscription ends (if cancelled)
  cancelAtPeriodEnd?: boolean; // Whether subscription is set to cancel at period end
  subscriptionStartDate?: string; // ISO timestamp when current subscription started
  trialEndDate?: string; // ISO timestamp when trial period ends (for trial notifications)
  billingCycle?: 'monthly' | 'annually'; // Billing cycle for current plan
  pendingPlan?: Plan | null; // Scheduled downgrade plan (effective at next renewal)
  pendingBillingCycle?: 'monthly' | 'annually' | null; // Scheduled downgrade billing cycle
  pendingPlanEffectiveDate?: string | null; // ISO timestamp when scheduled plan takes effect
  claimedReferralRewards?: Array<{
    milestone: number;
    type: string;
    amount: number;
    claimedAt: string;
  }>;
}

export interface Notification {
  id: string;
  text: string;
  timestamp: string;
  read: boolean;
  messageId?: string; // Optional - used for DM/comment links, or usage limit notifications
}

export interface Announcement {
  id: string;
  title: string;
  body: string;
  type: 'info' | 'warning' | 'success';
  isActive: boolean;
  isBanner: boolean; // show as top banner if true
  isPublic?: boolean; // if true, show to unauthenticated visitors (landing page)
  targetPlans?: Plan[]; // empty/undefined = all plans
  targetUserIds?: string[]; // empty/undefined = all users
  startsAt?: string; // ISO timestamp
  endsAt?: string; // ISO timestamp
  createdAt: string; // ISO timestamp
  createdBy: string; // admin uid
  updatedAt?: string; // ISO timestamp
  actionLabel?: string;
  actionPage?: Page; // internal navigation target
}

export type DashboardFilters = {
  platform: Platform | 'All';
  messageType: MessageType | 'All';
  sentiment: 'Positive' | 'Neutral' | 'Negative' | 'All';
  status: 'All' | 'Flagged' | 'Favorite';
  category: MessageCategory | 'All';
};

export interface DashboardNavState {
  filters: Partial<DashboardFilters>;
  highlightId?: string;
}

export interface TourStep {
  elementId: string;
  title: string;
  content: string;
  page?: Page;
  position?: 'top' | 'bottom' | 'left' | 'right';
}

export interface PaymentPlan {
  name: string;
  price: number;
  cycle: 'monthly' | 'annually';
}

export interface Toast {
  message: string;
  type: 'success' | 'error' | 'info';
}

export interface Activity {
    id: string;
    type: 'New User' | 'Plan Upgrade';
    user: { name: string; avatar: string; };
    details: string;
    timestamp: string;
}

export interface AutomationWorkflow {
  id: string;
  type: 'Caption' | 'Image' | 'Video';
  prompt: string;
  frequency: {
    type: 'Daily' | 'Weekly';
    count: number;
  };
  approvalType: 'Automatic' | 'Manual';
  isActive: boolean;
  lastRun: string;
  nextRun: string;
  generateCaptions?: boolean;
  useBaseImage?: boolean;
  goal?: string;
  tone?: string;
  generateVoiceOver?: boolean;
  voiceOverScript?: string;
  voice?: string;
  targetPlatforms?: Platform[];
  aspectRatio?: '16:9' | '9:16';
}

export type AutopilotStatus = 'Idle' | 'Strategizing' | 'Generating Content' | 'Complete' | 'Failed';

export interface CampaignPerformance {
    totalEngagement: number;
    totalViews: number;
    totalLikes: number;
    totalComments: number;
    totalShares: number;
    averageEngagementPerPost: number;
    averageViewsPerPost: number;
    engagementRate: number; // percentage
    postsPublished: number;
    postsScheduled: number;
    postsDraft: number;
    estimatedReach?: number;
    estimatedROI?: number; // For business users
    newFollowers?: number; // For creator users
    newLeads?: number; // For business users
}

export interface AutopilotCampaign {
    id: string;
    goal: string;
    niche: string;
    audience: string;
    status: AutopilotStatus;
    progress: number; 
    totalPosts: number;
    generatedPosts: number;
    createdAt: string;
    plan?: StrategyPlan; 
    hasAutopilot?: boolean; 
    performance?: CampaignPerformance;
}


export interface ApprovalItem {
  id: string;
  workflowId: string;
  generatedAt: string;
  type: 'Caption' | 'Image' | 'Video';
  content: {
    text?: string;
    hashtags?: string[];
    imageUrl?: string;
    videoUrl?: string;
  };
}

export interface CustomVoice {
  id: string;
  name: string;
  data?: string; // Base64 audio data (optional, may not be stored)
  mimeType: string;
  url?: string; // Firebase Storage URL
  elevenLabsVoiceId?: string; // ElevenLabs voice ID for cloned voices
  createdAt?: string;
  isCloned?: boolean; // Whether this is a cloned voice or uploaded sample
}

export interface ComposeContextData {
    topic: string;
    platform?: Platform;
    type?: 'Post' | 'Story' | 'Reel' | 'image' | 'video';
    date?: string;
    captionText?: string;
    hashtags?: string;
    generatedCaptions?: Array<{ caption: string; hashtags: string[] }>;
    media?: MediaItemState | null;
    results?: CaptionResult[];
    postGoal?: string;
    postTone?: string;
}

export interface MusicTrack {
    id: string;
    name: string;
    artist: string;
    url: string;
    duration: number; // in seconds
    genre?: string;
    mood?: string;
}

export interface MediaItemState {
    id: string;
    previewUrl: string;
    data: string;
    mimeType: string;
    type: 'image' | 'video';
    isGenerated?: boolean; // true if generated via AI, false/undefined if uploaded
    additionalImages?: Array<{ // Additional images for multi-image posts
        id: string;
        previewUrl: string;
        data: string;
        mimeType: string;
        results?: CaptionResult[];
        captionText?: string;
    }>;
    results: CaptionResult[];
    captionText: string;
    scheduledDate?: string; // Individual schedule date for this item
    postGoal: string; // Individual goal for this post
    postTone: string; // Individual tone for this post
    selectedPlatforms: Record<Platform, boolean>; // Individual platform selection per box
    selectedMusic?: MusicTrack; // Selected music track for Reels
    musicNote?: string; // Reminder note for adding music manually
    instagramPostType?: 'Post' | 'Reel' | 'Story'; // Instagram-specific post type
}

export interface ComposeState {
    media: {
        previewUrl: string;
        data: string;
        mimeType: string;
        type: 'image' | 'video';
        isGenerated?: boolean; // true if generated via AI, false/undefined if uploaded
    } | null;
    mediaItems: MediaItemState[]; // Array of media items for batch upload
    results: CaptionResult[];
    captionText: string;
    postGoal: string;
    postTone: string;
}

export interface CalendarEvent {
    id: string;
    title: string;
    date: string;
    type: 'Post' | 'Story' | 'Reel' | 'Email';
    platform: Platform;
    status: 'Scheduled' | 'Draft' | 'Published' | 'In Review';
    thumbnail?: string;
    description?: string;
}

export interface CRMNote {
    id: string;
    content: string;
    timestamp: string;
    author: string;
}

export interface CRMProfile {
    id: string; 
    name: string;
    avatar: string;
    tags: string[];
    notes: CRMNote[];
    email?: string;
    phone?: string;
    lifecycleStage?: 'Lead' | 'Customer' | 'Influencer' | 'Churned';
    aiSummary?: string;
}

export type ApprovalStatus = 'Draft' | 'In Review' | 'Approved' | 'Rejected' | 'Scheduled' | 'Published';

export interface PostComment {
    id: string;
    user: string; 
    text: string;
    timestamp: string;
}

export interface Post {
    id: string;
    content: string;
    mediaUrl?: string; // Single media URL (for backward compatibility)
    mediaUrls?: string[]; // Multiple media URLs (for multi-image posts)
    mediaType?: 'image' | 'video';
    platforms: Platform[];
    status: ApprovalStatus;
    author: { name: string; avatar: string };
    scheduledDate?: string;
    timestamp?: string;
    createdAt?: string;
    updatedAt?: string;
    publishedAt?: string;
    comments: PostComment[];
    clientId?: string; 
}

export interface DayPlan {
    dayOffset: number; 
    topic: string;
    format: 'Post' | 'Story' | 'Reel';
    platform: Platform;
    imageIdeas?: string[]; // AI-generated image ideas
    videoIdeas?: string[]; // AI-generated video ideas
    mediaUrl?: string; // Uploaded media URL
    mediaType?: 'image' | 'video'; // Type of uploaded media
    status?: 'draft' | 'ready' | 'scheduled' | 'posted'; // Status tracking
    linkedPostId?: string; // Links to actual Post when created
    caption?: string; // Caption for the post
    suggestedMediaType?: 'image' | 'video'; // Suggested type of media to upload
}

export interface WeekPlan {
    weekNumber: number;
    theme: string;
    content: DayPlan[];
}

export interface StrategyPlan {
    weeks: WeekPlan[];
    metrics?: {
        primaryKPI?: string;
        targetValue?: number;
        successCriteria?: string[];
        milestones?: Array<{
            week: number;
            description: string;
            targetMetric?: number;
        }>;
    };
}

/** Single idea from "What to Post" / generateDailyPostIdeas */
export interface DailyPostIdea {
    id: string;
    format: string;
    title: string;
    hook: string;
    shotList: string[];
    captionStarter?: string;
    cta?: string;
    hashtags: string[];
    whyThisWorks?: string;
    trendBased?: boolean;
    trendContext?: string;
    placeholderImage?: string;
    imageSource?: 'unsplash' | 'ai';
}

/** Settings used when generating daily ideas */
export interface WhatToPostSettings {
    platform: string;
    goal: string;
    effort: number;
    format: string;
    tone: string;
    useTrends?: boolean;
    spicyMode?: boolean;
}

/** Saved idea in Firestore (users/{uid}/savedIdeas) */
export interface SavedIdea {
    id: string;
    creatorId: string;
    createdAt: string;
    settings: WhatToPostSettings;
    idea: DailyPostIdea;
}

export interface VideoScene {
    id: string;
    prompt: string;
    status: 'pending' | 'generating' | 'completed' | 'failed';
    videoUrl?: string;
    duration: number;
    order?: number;
    onScreenText?: string;
    spokenLine?: string;
}

export interface AppContextType {
  isAuthLoading: boolean;
  isDarkMode: boolean;
  isAuthenticated: boolean;
  user: User | null;
  settings: Settings;
  clients: Client[];
  teamMembers: TeamMember[];
  selectedClient: Client | null;
  notifications: Notification[];
  announcements: Announcement[];
  dismissAnnouncement: (announcementId: string) => void;
  activePage: Page;
  isSidebarOpen: boolean;
  dashboardNavState: DashboardNavState | null;
  composeContext: ComposeContextData | null;
  composeState: ComposeState;
  isTourActive: boolean;
  tourStep: number;
  tourSteps: TourStep[];
  isPaymentModalOpen: boolean;
  paymentPlan: PaymentPlan | null;
  toast: Toast | null;
  userBaseImage: { data: string; mimeType: string } | null;
  userCustomVoices: CustomVoice[];
  messages: Message[];
  hashtagSets: HashtagSet[];
  posts: Post[];
  bioPage: BioPageConfig;
  calendarEvents: CalendarEvent[];
  autopilotCampaigns: AutopilotCampaign[];
  isCRMOpen: boolean;
  activeCRMProfileId: string | null;
  crmStore: Record<string, CRMProfile>; 
  toggleTheme: () => void;
  handleLogout: () => void;
  setUser: (user: Partial<User> | null) => Promise<void>;
  setSettings: (newSettings: Settings | React.SetStateAction<Settings>) => void;
  setClients: React.Dispatch<React.SetStateAction<Client[]>>;
  setTeamMembers: React.Dispatch<React.SetStateAction<TeamMember[]>>;
  setSelectedClient: React.Dispatch<React.SetStateAction<Client | null>>;
  setNotifications: React.Dispatch<React.SetStateAction<Notification[]>>;
  setActivePage: React.Dispatch<React.SetStateAction<Page>>;
  setIsSidebarOpen: React.Dispatch<React.SetStateAction<boolean>>;
  navigateToDashboardWithFilter: (filters: Partial<DashboardFilters>, highlightId?: string) => void;
  clearDashboardNavState: () => void;
  setComposeContext: (data: ComposeContextData) => void;
  clearComposeContext: () => void;
  setComposeState: React.Dispatch<React.SetStateAction<ComposeState>>;
  startTour: () => void;
  nextTourStep: () => void;
  endTour: () => void;
  openPaymentModal: (plan: PaymentPlan) => void;
  closePaymentModal: () => void;
  showToast: (message: string, type: 'success' | 'error' | 'info') => void;
  setUserBaseImage: React.Dispatch<React.SetStateAction<{ data: string; mimeType: string } | null>>;
  setUserCustomVoices: React.Dispatch<React.SetStateAction<CustomVoice[]>>;
  setMessages: React.Dispatch<React.SetStateAction<Message[]>>;
  setHashtagSets: React.Dispatch<React.SetStateAction<HashtagSet[]>>;
  setPosts: React.Dispatch<React.SetStateAction<Post[]>>;
  setBioPage: React.Dispatch<React.SetStateAction<BioPageConfig>>;
  saveBioPage: (config: BioPageConfig) => Promise<void>;
  setCalendarEvents: React.Dispatch<React.SetStateAction<CalendarEvent[]>>;
  addCalendarEvent: (event: CalendarEvent) => void;
  addAutopilotCampaign: (campaign: Omit<AutopilotCampaign, 'id' | 'createdAt' | 'progress' | 'totalPosts' | 'generatedPosts'>) => Promise<string>;
  updateAutopilotCampaign: (campaignId: string, data: Partial<AutopilotCampaign>) => Promise<void>;
  updateMessage: (id: string, data: Partial<Message>) => void;
  deleteMessage: (id: string) => void;
  categorizeAllMessages: () => void;
  updatePost: (post: Post) => Promise<void>;
  deletePost: (postId: string) => Promise<void>;
  openCRM: (user: { name: string; avatar: string }) => void;
  closeCRM: () => void;
  ensureCRMProfile: (user: { name: string; avatar: string }) => Promise<void>;
  addCRMNote: (profileId: string, note: string) => void;
  addCRMTag: (profileId: string, tag: string) => void;
  removeCRMTag: (profileId: string, tag: string) => void;
  updateCRMProfile: (profileId: string, data: Partial<CRMProfile>) => void;
  pricingView: 'Creator' | 'Business' | null;
  setPricingView: (view: 'Creator' | 'Business' | null) => void;
  selectedPlan: Plan | null;
  setSelectedPlan: (plan: Plan | null) => void;
  socialAccounts: Record<Platform, SocialAccount | null>;
}

// ==========================================
// Social Media OAuth & API Integration Types
// ==========================================

export interface SocialAccount {
  platform: Platform;
  connected: boolean;
  accessToken?: string; // Stored securely, encrypted in Firestore
  refreshToken?: string;
  expiresAt?: string; // ISO timestamp
  accountId?: string; // Platform-specific user/account ID
  accountName?: string; // Display name from platform
  accountUsername?: string; // Username/handle from platform
  lastSyncedAt?: string; // Last time we fetched data from this platform
}

export interface Promotion {
    id: string;
    code: string; // Unique promotion code (e.g., "SUMMER50", "FIRST10FREE")
    name: string; // Display name for the promotion
    description?: string;
    type: 'percentage' | 'fixed' | 'free'; // Discount type
    discountValue: number; // Percentage (0-100) or fixed amount in dollars, or 0 for free
    applicablePlans: Plan[]; // Which plans this promotion applies to (empty = all plans)
    startDate: string; // ISO timestamp
    endDate: string; // ISO timestamp (empty string = no expiration)
    maxUses?: number; // Maximum number of times this promotion can be used (undefined = unlimited)
    currentUses: number; // Current number of times used
    maxUsesPerUser?: number; // Maximum times a single user can use this (default: 1)
    isActive: boolean; // Admin can enable/disable without deleting
    createdAt: string; // ISO timestamp
    createdBy: string; // Admin user ID who created it
    freeDays?: number; // Number of free days to grant (for free promotions)
    discountDurationDays?: number; // Number of days the discount applies (for recurring subscriptions)
}

export interface PromotionUsage {
    id: string;
    promotionId: string;
    userId: string;
    userEmail: string;
    plan: Plan;
    originalPrice: number;
    discountedPrice: number;
    discountAmount: number;
    usedAt: string; // ISO timestamp
    expiresAt?: string; // ISO timestamp (for free days or discount duration)
}

// Update User interface to include social accounts
// This extends the User interface below
