

export interface Emoji {
  emoji: string;
  description: string;
  category: 'Smileys & People' | 'Animals & Nature' | 'Food & Drink' | 'Activities' | 'Travel & Places' | 'Objects' | 'Symbols';
  aliases: string[];
}

export const EMOJI_CATEGORIES = [
    { name: 'Smileys & People', icon: 'FaceSmileIcon' },
    { name: 'Animals & Nature', icon: 'CatIcon' },
    { name: 'Food & Drink', icon: 'PizzaIcon' },
    { name: 'Activities', icon: 'SoccerBallIcon' },
    { name: 'Travel & Places', icon: 'CarIcon' },
    { name: 'Objects', icon: 'LightbulbIcon' },
    { name: 'Symbols', icon: 'HeartIcon' },
] as const;


export const EMOJIS: Emoji[] = [
  // Smileys & People
  { emoji: '😀', description: 'grinning face', category: 'Smileys & People', aliases: ['happy', 'joy', 'grin'] },
  { emoji: '😃', description: 'grinning face with big eyes', category: 'Smileys & People', aliases: ['happy', 'joy', 'haha'] },
  { emoji: '😄', description: 'grinning face with smiling eyes', category: 'Smileys & People', aliases: ['happy', 'joy', 'laugh'] },
  { emoji: '😁', description: 'beaming face with smiling eyes', category: 'Smileys & People', aliases: ['grin', 'happy'] },
  { emoji: '😆', description: 'grinning squinting face', category: 'Smileys & People', aliases: ['happy', 'haha', 'lol'] },
  { emoji: '😅', description: 'grinning face with sweat', category: 'Smileys & People', aliases: ['hot', 'nervous'] },
  { emoji: '🤣', description: 'rolling on the floor laughing', category: 'Smileys & People', aliases: ['lol', 'rofl'] },
  { emoji: '😂', description: 'face with tears of joy', category: 'Smileys & People', aliases: ['laugh', 'cry'] },
  { emoji: '🙂', description: 'slightly smiling face', category: 'Smileys & People', aliases: ['smile', 'ok'] },
  { emoji: '🙃', description: 'upside-down face', category: 'Smileys & People', aliases: ['silly', 'sarcastic'] },
  { emoji: '😉', description: 'winking face', category: 'Smileys & People', aliases: ['wink', 'flirt'] },
  { emoji: '😊', description: 'smiling face with smiling eyes', category: 'Smileys & People', aliases: ['blush', 'proud'] },
  { emoji: '😇', description: 'smiling face with halo', category: 'Smileys & People', aliases: ['angel', 'innocent'] },
  { emoji: '🥰', description: 'smiling face with hearts', category: 'Smileys & People', aliases: ['love', 'crush'] },
  { emoji: '😍', description: 'smiling face with heart-eyes', category: 'Smileys & People', aliases: ['love', 'inlove'] },
  { emoji: '🤩', description: 'star-struck', category: 'Smileys & People', aliases: ['excited', 'wow'] },
  { emoji: '😘', description: 'face blowing a kiss', category: 'Smileys & People', aliases: ['kiss', 'flirt'] },
  { emoji: '😗', description: 'kissing face', category: 'Smileys & People', aliases: ['kiss'] },
  { emoji: '😚', description: 'kissing face with closed eyes', category: 'Smileys & People', aliases: ['kiss'] },
  { emoji: '😙', description: 'kissing face with smiling eyes', category: 'Smileys & People', aliases: ['kiss'] },
  { emoji: '😋', description: 'face savoring food', category: 'Smileys & People', aliases: ['yummy', 'delicious'] },
  { emoji: '😛', description: 'face with tongue', category: 'Smileys & People', aliases: ['silly', 'cheeky'] },
  { emoji: '😜', description: 'winking face with tongue', category: 'Smileys & People', aliases: ['joke', 'playful'] },
  { emoji: '🤪', description: 'zany face', category: 'Smileys & People', aliases: ['crazy', 'goofy'] },
  { emoji: '🤨', description: 'face with raised eyebrow', category: 'Smileys & People', aliases: ['suspicious', 'skeptical'] },
  { emoji: '🧐', description: 'face with monocle', category: 'Smileys & People', aliases: ['smart', 'investigate'] },
  { emoji: '🤓', description: 'nerd face', category: 'Smileys & People', aliases: ['geek', 'smart'] },
  { emoji: '😎', description: 'smiling face with sunglasses', category: 'Smileys & People', aliases: ['cool', 'win'] },
  { emoji: '🥳', description: 'partying face', category: 'Smileys & People', aliases: ['celebrate', 'party'] },
  { emoji: '😏', description: 'smirking face', category: 'Smileys & People', aliases: ['smug', 'smirk'] },
  { emoji: '😒', description: 'unamused face', category: 'Smileys & People', aliases: ['meh', 'annoyed'] },
  { emoji: '😞', description: 'disappointed face', category: 'Smileys & People', aliases: ['sad', 'bummed'] },
  { emoji: '😔', description: 'pensive face', category: 'Smileys & People', aliases: ['thoughtful', 'sad'] },
  { emoji: '😟', description: 'worried face', category: 'Smileys & People', aliases: ['concern'] },
  { emoji: '😕', description: 'confused face', category: 'Smileys & People', aliases: ['what'] },
  { emoji: '🙁', description: 'slightly frowning face', category: 'Smileys & People', aliases: ['sad'] },
  { emoji: '😣', description: 'persevering face', category: 'Smileys & People', aliases: ['struggle'] },
  { emoji: '😖', description: 'confounded face', category: 'Smileys & People', aliases: ['frustrated'] },
  { emoji: '😫', description: 'tired face', category: 'Smileys & People', aliases: ['exhausted'] },
  { emoji: '😩', description: 'weary face', category: 'Smileys & People', aliases: ['overwhelmed'] },
  { emoji: '🥺', description: 'pleading face', category: 'Smileys & People', aliases: ['puppy eyes', 'begging'] },
  { emoji: '😭', description: 'loudly crying face', category: 'Smileys & People', aliases: ['sad', 'cry'] },
  { emoji: '😤', description: 'face with steam from nose', category: 'Smileys & People', aliases: ['triumph', 'frustrated'] },
  { emoji: '😠', description: 'angry face', category: 'Smileys & People', aliases: ['mad'] },
  { emoji: '😡', description: 'pouting face', category: 'Smileys & People', aliases: ['angry', 'mad'] },
  { emoji: '🤬', description: 'face with symbols on mouth', category: 'Smileys & People', aliases: ['swearing', 'cursing'] },
  { emoji: '🤯', description: 'exploding head', category: 'Smileys & People', aliases: ['mind blown', 'shocked'] },
  { emoji: '😳', description: 'flushed face', category: 'Smileys & People', aliases: ['embarrassed', 'shy'] },
  { emoji: '🥵', description: 'hot face', category: 'Smileys & People', aliases: ['sweating', 'heat'] },
  { emoji: '🥶', description: 'cold face', category: 'Smileys & People', aliases: ['freezing', 'ice'] },
  { emoji: '😱', description: 'face screaming in fear', category: 'Smileys & People', aliases: ['scream', 'shock'] },
  { emoji: '😨', description: 'fearful face', category: 'Smileys & People', aliases: ['scared'] },
  { emoji: '😰', description: 'anxious face with sweat', category: 'Smileys & People', aliases: ['nervous'] },
  { emoji: '😥', description: 'sad but relieved face', category: 'Smileys & People', aliases: ['phew'] },
  { emoji: '😓', description: 'downcast face with sweat', category: 'Smileys & People', aliases: ['sad'] },
  { emoji: '🤗', description: 'hugging face', category: 'Smileys & People', aliases: ['hug'] },
  { emoji: '🤔', description: 'thinking face', category: 'Smileys & People', aliases: ['hmmm', 'idea'] },
  { emoji: '🤭', description: 'face with hand over mouth', category: 'Smileys & People', aliases: ['oops', 'giggle'] },
  { emoji: '🤫', description: 'shushing face', category: 'Smileys & People', aliases: ['secret', 'quiet'] },
  { emoji: '🤥', description: 'lying face', category: 'Smileys & People', aliases: ['pinocchio'] },
  { emoji: '😶', description: 'face without mouth', category: 'Smileys & People', aliases: ['speechless', 'silent'] },
  { emoji: '😐', description: 'neutral face', category: 'Smileys & People', aliases: ['straight face'] },
  { emoji: '😑', description: 'expressionless face', category: 'Smileys & People', aliases: ['annoyed'] },
  { emoji: '😬', description: 'grimacing face', category: 'Smileys & People', aliases: ['awkward', 'cringe'] },
  { emoji: '🙄', description: 'face with rolling eyes', category: 'Smileys & People', aliases: ['eyeroll', 'whatever'] },
  { emoji: '😯', description: 'hushed face', category: 'Smileys & People', aliases: ['surprised'] },
  { emoji: '😦', description: 'frowning face with open mouth', category: 'Smileys & People', aliases: ['shock'] },
  { emoji: '😧', description: 'anguished face', category: 'Smileys & People', aliases: ['pain'] },
  { emoji: '😮', description: 'face with open mouth', category: 'Smileys & People', aliases: ['wow', 'omg'] },
  { emoji: '😲', description: 'astonished face', category: 'Smileys & People', aliases: ['shocked'] },
  { emoji: '😴', description: 'sleeping face', category: 'Smileys & People', aliases: ['zzz', 'tired'] },
  { emoji: '🤤', description: 'drooling face', category: 'Smileys & People', aliases: ['hungry'] },
  { emoji: '😪', description: 'sleepy face', category: 'Smileys & People', aliases: ['tired'] },
  { emoji: '😵', description: 'dizzy face', category: 'Smileys & People', aliases: ['knocked out'] },
  { emoji: '🤐', description: 'zipper-mouth face', category: 'Smileys & People', aliases: ['secret', 'sealed lips'] },
  { emoji: '🥴', description: 'woozy face', category: 'Smileys & People', aliases: ['drunk'] },
  { emoji: '🤢', description: 'nauseated face', category: 'Smileys & People', aliases: ['sick', 'disgusted'] },
  { emoji: '🤮', description: 'face vomiting', category: 'Smileys & People', aliases: ['puke', 'throw up'] },
  { emoji: '🤧', description: 'sneezing face', category: 'Smileys & People', aliases: ['gesundheit', 'sick'] },
  { emoji: '😷', description: 'face with medical mask', category: 'Smileys & People', aliases: ['sick', 'covid'] },
  { emoji: '🤒', description: 'face with thermometer', category: 'Smileys & People', aliases: ['sick', 'fever'] },
  { emoji: '🤕', description: 'face with head-bandage', category: 'Smileys & People', aliases: ['injured', 'hurt'] },
  { emoji: '🤑', description: 'money-mouth face', category: 'Smileys & People', aliases: ['rich', 'dollar'] },
  { emoji: '🤠', description: 'cowboy hat face', category: 'Smileys & People', aliases: ['yeehaw'] },
  { emoji: '😈', description: 'smiling face with horns', category: 'Smileys & People', aliases: ['devil', 'evil'] },
  { emoji: '👿', description: 'angry face with horns', category: 'Smileys & People', aliases: ['devil', 'imp'] },
  { emoji: '🤡', description: 'clown face', category: 'Smileys & People', aliases: ['fool'] },
  { emoji: '💩', description: 'pile of poo', category: 'Smileys & People', aliases: ['crap', 'poop'] },
  { emoji: '👻', description: 'ghost', category: 'Smileys & People', aliases: ['halloween', 'spooky'] },
  { emoji: '💀', description: 'skull', category: 'Smileys & People', aliases: ['dead', 'death'] },
  { emoji: '👽', description: 'alien', category: 'Smileys & People', aliases: ['ufo', 'space'] },
  { emoji: '👾', description: 'alien monster', category: 'Smileys & People', aliases: ['space invader', 'game'] },
  { emoji: '🤖', description: 'robot', category: 'Smileys & People', aliases: ['ai', 'bot'] },
  { emoji: '🎃', description: 'jack-o-lantern', category: 'Smileys & People', aliases: ['halloween', 'pumpkin'] },
  { emoji: '👋', description: 'waving hand', category: 'Smileys & People', aliases: ['hello', 'goodbye'] },
  { emoji: '🤚', description: 'raised back of hand', category: 'Smileys & People', aliases: ['stop'] },
  { emoji: '🖐️', description: 'hand with fingers splayed', category: 'Smileys & People', aliases: ['high five'] },
  { emoji: '✋', description: 'raised hand', category: 'Smileys & People', aliases: ['stop'] },
  { emoji: '🖖', description: 'vulcan salute', category: 'Smileys & People', aliases: ['spock', 'star trek'] },
  { emoji: '👌', description: 'OK hand', category: 'Smileys & People', aliases: ['perfect', 'good'] },
  { emoji: '🤌', description: 'pinched fingers', category: 'Smileys & People', aliases: ['italian'] },
  { emoji: '🤏', description: 'pinching hand', category: 'Smileys & People', aliases: ['small'] },
  { emoji: '✌️', description: 'victory hand', category: 'Smileys & People', aliases: ['peace', 'win'] },
  { emoji: '🤞', description: 'crossed fingers', category: 'Smileys & People', aliases: ['luck', 'hope'] },
  { emoji: '🤟', description: 'love-you gesture', category: 'Smileys & People', aliases: ['ily', 'rock on'] },
  { emoji: '🤘', description: 'sign of the horns', category: 'Smileys & People', aliases: ['rock'] },
  { emoji: '🤙', description: 'call me hand', category: 'Smileys & People', aliases: ['shaka'] },
  { emoji: '👈', description: 'backhand index pointing left', category: 'Smileys & People', aliases: ['point'] },
  { emoji: '👉', description: 'backhand index pointing right', category: 'Smileys & People', aliases: ['point'] },
  { emoji: '👆', description: 'backhand index pointing up', category: 'Smileys & People', aliases: ['point'] },
  { emoji: '🖕', description: 'middle finger', category: 'Smileys & People', aliases: ['fu'] },
  { emoji: '👇', description: 'backhand index pointing down', category: 'Smileys & People', aliases: ['point'] },
  { emoji: '👍', description: 'thumbs up', category: 'Smileys & People', aliases: ['like', 'yes'] },
  { emoji: '👎', description: 'thumbs down', category: 'Smileys & People', aliases: ['dislike', 'no'] },
  { emoji: '✊', description: 'raised fist', category: 'Smileys & People', aliases: ['power', 'fist'] },
  { emoji: '👊', description: 'oncoming fist', category: 'Smileys & People', aliases: ['fist bump', 'bro'] },
  { emoji: '👏', description: 'clapping hands', category: 'Smileys & People', aliases: ['applause', 'clap'] },
  { emoji: '🙌', description: 'raising hands', category: 'Smileys & People', aliases: ['praise', 'celebrate'] },
  { emoji: '👐', description: 'open hands', category: 'Smileys & People', aliases: ['hug'] },
  { emoji: '🤝', description: 'handshake', category: 'Smileys & People', aliases: ['deal', 'agreement'] },
  { emoji: '🙏', description: 'folded hands', category: 'Smileys & People', aliases: ['please', 'thank you', 'pray'] },
  { emoji: '✍️', description: 'writing hand', category: 'Smileys & People', aliases: ['write'] },
  { emoji: '💅', description: 'nail polish', category: 'Smileys & People', aliases: ['manicure', 'beauty'] },
  { emoji: '🤳', description: 'selfie', category: 'Smileys & People', aliases: ['photo'] },
  { emoji: '💪', description: 'flexed biceps', category: 'Smileys & People', aliases: ['strong', 'muscle'] },
  { emoji: '🧠', description: 'brain', category: 'Smileys & People', aliases: ['mind', 'smart'] },
  { emoji: '👀', description: 'eyes', category: 'Smileys & People', aliases: ['watching', 'curious'] },
  { emoji: '🗣️', description: 'speaking head', category: 'Smileys & People', aliases: ['talk'] },
  { emoji: '👤', description: 'bust in silhouette', category: 'Smileys & People', aliases: ['user', 'person'] },
  { emoji: '👥', description: 'busts in silhouette', category: 'Smileys & People', aliases: ['group', 'team'] },
  { emoji: '🚶', description: 'person walking', category: 'Smileys & People', aliases: ['walk'] },
  { emoji: '🏃', description: 'person running', category: 'Smileys & People', aliases: ['run', 'fast'] },
  { emoji: '💃', description: 'woman dancing', category: 'Smileys & People', aliases: ['dance'] },
  { emoji: '🕺', description: 'man dancing', category: 'Smileys & People', aliases: ['dance'] },
  { emoji: '🤦', description: 'person facepalming', category: 'Smileys & People', aliases: ['facepalm'] },
  { emoji: '🤷', description: 'person shrugging', category: 'Smileys & People', aliases: ['shrug', 'dunno'] },
  { emoji: '👑', description: 'crown', category: 'Smileys & People', aliases: ['king', 'queen', 'royal'] },
  { emoji: '💦', description: 'sweat droplets', category: 'Smileys & People', aliases: ['splashing', 'water', 'gushing'] },


  // Animals & Nature
  { emoji: '🐶', description: 'dog face', category: 'Animals & Nature', aliases: ['puppy', 'pet'] },
  { emoji: '🐱', description: 'cat face', category: 'Animals & Nature', aliases: ['kitty', 'pet'] },
  { emoji: '🐭', description: 'mouse face', category: 'Animals & Nature', aliases: ['rodent'] },
  { emoji: '🐹', description: 'hamster', category: 'Animals & Nature', aliases: ['pet'] },
  { emoji: '🐰', description: 'rabbit face', category: 'Animals & Nature', aliases: ['bunny', 'pet'] },
  { emoji: '🦊', description: 'fox', category: 'Animals & Nature', aliases: ['sly'] },
  { emoji: '🐻', description: 'bear', category: 'Animals & Nature', aliases: ['grizzly'] },
  { emoji: '🐼', description: 'panda', category: 'Animals & Nature', aliases: ['bamboo'] },
  { emoji: '🐨', description: 'koala', category: 'Animals & Nature', aliases: ['australia'] },
  { emoji: '🐯', description: 'tiger face', category: 'Animals & Nature', aliases: ['cat'] },
  { emoji: '🦁', description: 'lion', category: 'Animals & Nature', aliases: ['king'] },
  { emoji: '🐮', description: 'cow face', category: 'Animals & Nature', aliases: ['farm'] },
  { emoji: '🐷', description: 'pig face', category: 'Animals & Nature', aliases: ['farm', 'oink'] },
  { emoji: '🐵', description: 'monkey face', category: 'Animals & Nature', aliases: ['primate'] },
  { emoji: '🦄', description: 'unicorn', category: 'Animals & Nature', aliases: ['magic', 'fantasy'] },
  { emoji: '🦋', description: 'butterfly', category: 'Animals & Nature', aliases: ['insect', 'pretty'] },
  { emoji: '🐛', description: 'bug', category: 'Animals & Nature', aliases: ['insect'] },
  { emoji: '🐝', description: 'honeybee', category: 'Animals & Nature', aliases: ['bee', 'buzz'] },
  { emoji: '🐞', description: 'lady beetle', category: 'Animals & Nature', aliases: ['ladybug'] },
  { emoji: '🐢', description: 'turtle', category: 'Animals & Nature', aliases: ['slow'] },
  { emoji: '🐍', description: 'snake', category: 'Animals & Nature', aliases: ['hiss'] },
  { emoji: '🦎', description: 'lizard', category: 'Animals & Nature', aliases: ['reptile'] },
  { emoji: '🐙', description: 'octopus', category: 'Animals & Nature', aliases: ['tentacles'] },
  { emoji: '🦑', description: 'squid', category: 'Animals & Nature', aliases: ['ocean'] },
  { emoji: '🦐', description: 'shrimp', category: 'Animals & Nature', aliases: ['seafood'] },
  { emoji: '🦀', description: 'crab', category: 'Animals & Nature', aliases: ['beach'] },
  { emoji: '🐡', description: 'blowfish', category: 'Animals & Nature', aliases: ['pufferfish'] },
  { emoji: '🐠', description: 'tropical fish', category: 'Animals & Nature', aliases: ['nemo'] },
  { emoji: '🐟', description: 'fish', category: 'Animals & Nature', aliases: ['ocean'] },
  { emoji: '🐬', description: 'dolphin', category: 'Animals & Nature', aliases: ['flipper'] },
  { emoji: '🐳', description: 'spouting whale', category: 'Animals & Nature', aliases: ['ocean'] },
  { emoji: '🐋', description: 'whale', category: 'Animals & Nature', aliases: ['ocean'] },
  { emoji: '🦈', description: 'shark', category: 'Animals & Nature', aliases: ['jaws'] },
  { emoji: '🐊', description: 'crocodile', category: 'Animals & Nature', aliases: ['alligator'] },
  { emoji: '🐅', description: 'tiger', category: 'Animals & Nature', aliases: ['cat'] },
  { emoji: '🐆', description: 'leopard', category: 'Animals & Nature', aliases: ['cat'] },
  { emoji: '🦓', description: 'zebra', category: 'Animals & Nature', aliases: ['stripes'] },
  { emoji: '🦍', description: 'gorilla', category: 'Animals & Nature', aliases: ['ape'] },
  { emoji: '🦧', description: 'orangutan', category: 'Animals & Nature', aliases: ['ape'] },
  { emoji: '🐘', description: 'elephant', category: 'Animals & Nature', aliases: ['pachyderm'] },
  { emoji: '🦛', description: 'hippopotamus', category: 'Animals & Nature', aliases: ['hippo'] },
  { emoji: '🦏', description: 'rhinoceros', category: 'Animals & Nature', aliases: ['rhino'] },
  { emoji: '🐪', description: 'camel', category: 'Animals & Nature', aliases: ['desert'] },
  { emoji: '🦒', description: 'giraffe', category: 'Animals & Nature', aliases: ['long neck'] },
  { emoji: '🦘', description: 'kangaroo', category: 'Animals & Nature', aliases: ['australia'] },
  { emoji: '🐃', description: 'water buffalo', category: 'Animals & Nature', aliases: ['bison'] },
  { emoji: '🐄', description: 'cow', category: 'Animals & Nature', aliases: ['farm'] },
  { emoji: '🐎', description: 'horse', category: 'Animals & Nature', aliases: ['race'] },
  { emoji: '🐖', description: 'pig', category: 'Animals & Nature', aliases: ['farm'] },
  { emoji: '🐏', description: 'ram', category: 'Animals & Nature', aliases: ['sheep'] },
  { emoji: '🐐', description: 'goat', category: 'Animals & Nature', aliases: ['farm'] },
  { emoji: '🐕', description: 'dog', category: 'Animals & Nature', aliases: ['pet'] },
  { emoji: '🐩', description: 'poodle', category: 'Animals & Nature', aliases: ['dog'] },
  { emoji: '🐓', description: 'rooster', category: 'Animals & Nature', aliases: ['chicken'] },
  { emoji: '🦃', description: 'turkey', category: 'Animals & Nature', aliases: ['thanksgiving'] },
  { emoji: '🦅', description: 'eagle', category: 'Animals & Nature', aliases: ['america'] },
  { emoji: '🦆', description: 'duck', category: 'Animals & Nature', aliases: ['quack'] },
  { emoji: '🦢', description: 'swan', category: 'Animals & Nature', aliases: ['bird'] },
  { emoji: '🦉', description: 'owl', category: 'Animals & Nature', aliases: ['wise'] },
  { emoji: '🦩', description: 'flamingo', category: 'Animals & Nature', aliases: ['pink'] },
  { emoji: '🦚', description: 'peacock', category: 'Animals & Nature', aliases: ['proud'] },
  { emoji: '🦜', description: 'parrot', category: 'Animals & Nature', aliases: ['bird'] },
  { emoji: '🐸', description: 'frog', category: 'Animals & Nature', aliases: ['ribbit'] },
  { emoji: '🌹', description: 'rose', category: 'Animals & Nature', aliases: ['flower', 'love'] },
  { emoji: '🥀', description: 'wilted flower', category: 'Animals & Nature', aliases: ['sad'] },
  { emoji: '🌺', description: 'hibiscus', category: 'Animals & Nature', aliases: ['flower'] },
  { emoji: '🌻', description: 'sunflower', category: 'Animals & Nature', aliases: ['flower', 'happy'] },
  { emoji: '🌼', description: 'blossom', category: 'Animals & Nature', aliases: ['flower'] },
  { emoji: '🌷', description: 'tulip', category: 'Animals & Nature', aliases: ['flower'] },
  { emoji: '🌱', description: 'seedling', category: 'Animals & Nature', aliases: ['plant', 'grow'] },
  { emoji: '🌲', description: 'evergreen tree', category: 'Animals & Nature', aliases: ['pine', 'forest'] },
  { emoji: '🌳', description: 'deciduous tree', category: 'Animals & Nature', aliases: ['forest'] },
  { emoji: '🌴', description: 'palm tree', category: 'Animals & Nature', aliases: ['beach', 'tropical'] },
  { emoji: '🌵', description: 'cactus', category: 'Animals & Nature', aliases: ['desert'] },
  { emoji: '🌾', description: 'sheaf of rice', category: 'Animals & Nature', aliases: ['plant'] },
  { emoji: '🌿', description: 'herb', category: 'Animals & Nature', aliases: ['leaf'] },
  { emoji: '🍀', description: 'four leaf clover', category: 'Animals & Nature', aliases: ['luck', 'irish'] },
  { emoji: '🍁', description: 'maple leaf', category: 'Animals & Nature', aliases: ['canada', 'autumn'] },
  { emoji: '🍄', description: 'mushroom', category: 'Animals & Nature', aliases: ['fungus'] },
  { emoji: '🔥', description: 'fire', category: 'Animals & Nature', aliases: ['hot', 'lit'] },
  { emoji: '✨', description: 'sparkles', category: 'Animals & Nature', aliases: ['magic', 'shiny'] },
  { emoji: '⭐', description: 'star', category: 'Animals & Nature', aliases: ['night', 'shiny'] },
  { emoji: '☀️', description: 'sun', category: 'Animals & Nature', aliases: ['weather', 'bright'] },
  { emoji: '🌙', description: 'crescent moon', category: 'Animals & Nature', aliases: ['night', 'sleep'] },
  { emoji: '☁️', description: 'cloud', category: 'Animals & Nature', aliases: ['weather'] },
  { emoji: '🌬️', description: 'wind face', category: 'Animals & Nature', aliases: ['blow'] },
  { emoji: '🌊', description: 'water wave', category: 'Animals & Nature', aliases: ['ocean', 'sea'] },
  { emoji: '🌎', description: 'globe showing Americas', category: 'Animals & Nature', aliases: ['world', 'earth'] },

  // Food & Drink
  { emoji: '🍇', description: 'grapes', category: 'Food & Drink', aliases: ['fruit'] },
  { emoji: '🍈', description: 'melon', category: 'Food & Drink', aliases: ['fruit'] },
  { emoji: '🍉', description: 'watermelon', category: 'Food & Drink', aliases: ['fruit'] },
  { emoji: '🍊', description: 'tangerine', category: 'Food & Drink', aliases: ['orange', 'fruit'] },
  { emoji: '🍋', description: 'lemon', category: 'Food & Drink', aliases: ['fruit'] },
  { emoji: '🍌', description: 'banana', category: 'Food & Drink', aliases: ['fruit'] },
  { emoji: '🍍', description: 'pineapple', category: 'Food & Drink', aliases: ['fruit'] },
  { emoji: '🍎', description: 'red apple', category: 'Food & Drink', aliases: ['fruit'] },
  { emoji: '🍏', description: 'green apple', category: 'Food & Drink', aliases: ['fruit'] },
  { emoji: '🍐', description: 'pear', category: 'Food & Drink', aliases: ['fruit'] },
  { emoji: '🍑', description: 'peach', category: 'Food & Drink', aliases: ['fruit'] },
  { emoji: '🍒', description: 'cherries', category: 'Food & Drink', aliases: ['fruit'] },
  { emoji: '🍓', description: 'strawberry', category: 'Food & Drink', aliases: ['fruit', 'berry'] },
  { emoji: '🥝', description: 'kiwi fruit', category: 'Food & Drink', aliases: ['fruit'] },
  { emoji: '🍅', description: 'tomato', category: 'Food & Drink', aliases: ['vegetable', 'fruit'] },
  { emoji: '🥥', description: 'coconut', category: 'Food & Drink', aliases: ['fruit', 'tropical'] },
  { emoji: '🥑', description: 'avocado', category: 'Food & Drink', aliases: ['fruit', 'food'] },
  { emoji: '🍆', description: 'eggplant', category: 'Food & Drink', aliases: ['aubergine', 'vegetable'] },
  { emoji: '🥔', description: 'potato', category: 'Food & Drink', aliases: ['vegetable'] },
  { emoji: '🥕', description: 'carrot', category: 'Food & Drink', aliases: ['vegetable'] },
  { emoji: '🌽', description: 'ear of corn', category: 'Food & Drink', aliases: ['vegetable'] },
  { emoji: '🌶️', description: 'hot pepper', category: 'Food & Drink', aliases: ['spicy'] },
  { emoji: '🥒', description: 'cucumber', category: 'Food & Drink', aliases: ['vegetable'] },
  { emoji: '🥬', description: 'leafy green', category: 'Food & Drink', aliases: ['lettuce', 'salad'] },
  { emoji: '🥦', description: 'broccoli', category: 'Food & Drink', aliases: ['vegetable'] },
  { emoji: '🧄', description: 'garlic', category: 'Food & Drink', aliases: ['flavoring'] },
  { emoji: '🧅', description: 'onion', category: 'Food & Drink', aliases: ['flavoring'] },
  { emoji: '🍄', description: 'mushroom', category: 'Food & Drink', aliases: ['vegetable'] },
  { emoji: '🥜', description: 'peanuts', category: 'Food & Drink', aliases: ['nut'] },
  { emoji: '🌰', description: 'chestnut', category: 'Food & Drink', aliases: ['nut'] },
  { emoji: '🍞', description: 'bread', category: 'Food & Drink', aliases: ['toast'] },
  { emoji: '🥐', description: 'croissant', category: 'Food & Drink', aliases: ['pastry'] },
  { emoji: '🥖', description: 'baguette bread', category: 'Food & Drink', aliases: ['french'] },
  { emoji: '🥨', description: 'pretzel', category: 'Food & Drink', aliases: ['snack'] },
  { emoji: '🥯', description: 'bagel', category: 'Food & Drink', aliases: ['bread'] },
  { emoji: '🥞', description: 'pancakes', category: 'Food & Drink', aliases: ['breakfast'] },
  { emoji: '🧇', description: 'waffle', category: 'Food & Drink', aliases: ['breakfast'] },
  { emoji: '🧀', description: 'cheese wedge', category: 'Food & Drink', aliases: ['dairy'] },
  { emoji: '🍖', description: 'meat on bone', category: 'Food & Drink', aliases: ['steak'] },
  { emoji: '🍗', description: 'poultry leg', category: 'Food & Drink', aliases: ['chicken', 'drumstick'] },
  { emoji: '🥩', description: 'cut of meat', category: 'Food & Drink', aliases: ['steak'] },
  { emoji: '🥓', description: 'bacon', category: 'Food & Drink', aliases: ['pork'] },
  { emoji: '🍔', description: 'hamburger', category: 'Food & Drink', aliases: ['burger', 'fast food'] },
  { emoji: '🍟', description: 'french fries', category: 'Food & Drink', aliases: ['chips'] },
  { emoji: '🍕', description: 'pizza', category: 'Food & Drink', aliases: ['slice'] },
  { emoji: '🌭', description: 'hot dog', category: 'Food & Drink', aliases: ['frankfurter'] },
  { emoji: '🥪', description: 'sandwich', category: 'Food & Drink', aliases: ['lunch'] },
  { emoji: '🌮', description: 'taco', category: 'Food & Drink', aliases: ['mexican'] },
  { emoji: '🌯', description: 'burrito', category: 'Food & Drink', aliases: ['mexican'] },
  { emoji: '🥙', description: 'stuffed flatbread', category: 'Food & Drink', aliases: ['kebab'] },
  { emoji: '🧆', description: 'falafel', category: 'Food & Drink', aliases: ['chickpea'] },
  { emoji: '🥚', description: 'egg', category: 'Food & Drink', aliases: ['breakfast'] },
  { emoji: '🍳', description: 'cooking', category: 'Food & Drink', aliases: ['fried egg'] },
  { emoji: '🥘', description: 'shallow pan of food', category: 'Food & Drink', aliases: ['paella'] },
  { emoji: '🍲', description: 'pot of food', category: 'Food & Drink', aliases: ['soup', 'stew'] },
  { emoji: '🥣', description: 'bowl with spoon', category: 'Food & Drink', aliases: ['cereal', 'soup'] },
  { emoji: '🥗', description: 'green salad', category: 'Food & Drink', aliases: ['healthy'] },
  { emoji: '🍿', description: 'popcorn', category: 'Food & Drink', aliases: ['movie'] },
  { emoji: '🧈', description: 'butter', category: 'Food & Drink', aliases: ['dairy'] },
  { emoji: '🧂', description: 'salt', category: 'Food & Drink', aliases: ['shaker'] },
  { emoji: '🥫', description: 'canned food', category: 'Food & Drink', aliases: ['can'] },
  { emoji: '🍱', description: 'bento box', category: 'Food & Drink', aliases: ['japanese', 'lunch'] },
  { emoji: '🍘', description: 'rice cracker', category: 'Food & Drink', aliases: ['japanese'] },
  { emoji: '🍙', description: 'rice ball', category: 'Food & Drink', aliases: ['onigiri', 'japanese'] },
  { emoji: '🍚', description: 'cooked rice', category: 'Food & Drink', aliases: ['food'] },
  { emoji: '🍛', description: 'curry rice', category: 'Food & Drink', aliases: ['indian'] },
  { emoji: '🍜', description: 'steaming bowl', category: 'Food & Drink', aliases: ['ramen', 'noodles'] },
  { emoji: '🍝', description: 'spaghetti', category: 'Food & Drink', aliases: ['pasta', 'italian'] },
  { emoji: '🍠', description: 'roasted sweet potato', category: 'Food & Drink', aliases: ['food'] },
  { emoji: '🍢', description: 'oden', category: 'Food & Drink', aliases: ['japanese'] },
  { emoji: '🍣', description: 'sushi', category: 'Food & Drink', aliases: ['japanese', 'fish'] },
  { emoji: '🍤', description: 'fried shrimp', category: 'Food & Drink', aliases: ['tempura'] },
  { emoji: '🍥', description: 'fish cake with swirl', category: 'Food & Drink', aliases: ['naruto'] },
  { emoji: '🥮', description: 'moon cake', category: 'Food & Drink', aliases: ['autumn'] },
  { emoji: '🍡', description: 'dango', category: 'Food & Drink', aliases: ['japanese', 'dessert'] },
  { emoji: '🥟', description: 'dumpling', category: 'Food & Drink', aliases: ['chinese'] },
  { emoji: '🥠', description: 'fortune cookie', category: 'Food & Drink', aliases: ['chinese'] },
  { emoji: '🥡', description: 'takeout box', category: 'Food & Drink', aliases: ['chinese'] },
  { emoji: '🦀', description: 'crab', category: 'Food & Drink', aliases: ['crustacean'] },
  { emoji: '🦞', description: 'lobster', category: 'Food & Drink', aliases: ['seafood'] },
  { emoji: '🦐', description: 'shrimp', category: 'Food & Drink', aliases: ['seafood'] },
  { emoji: '🦑', description: 'squid', category: 'Food & Drink', aliases: ['seafood'] },
  { emoji: '🦪', description: 'oyster', category: 'Food & Drink', aliases: ['seafood'] },
  { emoji: '🍦', description: 'soft ice cream', category: 'Food & Drink', aliases: ['dessert'] },
  { emoji: '🍧', description: 'shaved ice', category: 'Food & Drink', aliases: ['dessert'] },
  { emoji: '🍨', description: 'ice cream', category: 'Food & Drink', aliases: ['dessert'] },
  { emoji: '🍩', description: 'doughnut', category: 'Food & Drink', aliases: ['dessert', 'donut'] },
  { emoji: '🍪', description: 'cookie', category: 'Food & Drink', aliases: ['biscuit'] },
  { emoji: '🎂', description: 'birthday cake', category: 'Food & Drink', aliases: ['party', 'dessert'] },
  { emoji: '🍰', description: 'shortcake', category: 'Food & Drink', aliases: ['cake', 'dessert'] },
  { emoji: '🧁', description: 'cupcake', category: 'Food & Drink', aliases: ['dessert'] },
  { emoji: '🥧', description: 'pie', category: 'Food & Drink', aliases: ['dessert'] },
  { emoji: '🍫', description: 'chocolate bar', category: 'Food & Drink', aliases: ['candy'] },
  { emoji: '🍬', description: 'candy', category: 'Food & Drink', aliases: ['sweet'] },
  { emoji: '🍭', description: 'lollipop', category: 'Food & Drink', aliases: ['candy'] },
  { emoji: '🍮', description: 'custard', category: 'Food & Drink', aliases: ['dessert'] },
  { emoji: '🍯', description: 'honey pot', category: 'Food & Drink', aliases: ['sweet'] },
  { emoji: '🍼', description: 'baby bottle', category: 'Food & Drink', aliases: ['milk'] },
  { emoji: '🥛', description: 'glass of milk', category: 'Food & Drink', aliases: ['drink'] },
  { emoji: '☕', description: 'hot beverage', category: 'Food & Drink', aliases: ['coffee', 'tea'] },
  { emoji: '🍵', description: 'teacup without handle', category: 'Food & Drink', aliases: ['tea', 'green'] },
  { emoji: '🍶', description: 'sake', category: 'Food & Drink', aliases: ['japanese', 'drink'] },
  { emoji: '🍾', description: 'bottle with popping cork', category: 'Food & Drink', aliases: ['champagne', 'celebrate'] },
  { emoji: '🍷', description: 'wine glass', category: 'Food & Drink', aliases: ['drink', 'bar'] },
  { emoji: '🍸', description: 'cocktail glass', category: 'Food & Drink', aliases: ['drink', 'bar'] },
  { emoji: '🍹', description: 'tropical drink', category: 'Food & Drink', aliases: ['cocktail', 'vacation'] },
  { emoji: '🍺', description: 'beer mug', category: 'Food & Drink', aliases: ['drink', 'bar'] },
  { emoji: '🍻', description: 'clinking beer mugs', category: 'Food & Drink', aliases: ['cheers', 'bar'] },
  { emoji: '🥂', description: 'clinking glasses', category: 'Food & Drink', aliases: ['cheers', 'celebrate'] },
  { emoji: '🥃', description: 'tumbler glass', category: 'Food & Drink', aliases: ['whiskey'] },
  { emoji: '🥤', description: 'cup with straw', category: 'Food & Drink', aliases: ['soda'] },
  { emoji: '🧋', description: 'bubble tea', category: 'Food & Drink', aliases: ['boba'] },
  { emoji: '🧉', description: 'mate', category: 'Food & Drink', aliases: ['drink'] },
  { emoji: '🧊', description: 'ice cube', category: 'Food & Drink', aliases: ['cold'] },
  { emoji: '🥢', description: 'chopsticks', category: 'Food & Drink', aliases: ['asian'] },
  { emoji: '🍽️', description: 'fork and knife with plate', category: 'Food & Drink', aliases: ['eat'] },
  { emoji: '🍴', description: 'fork and knife', category: 'Food & Drink', aliases: ['cutlery'] },
  { emoji: '🥄', description: 'spoon', category: 'Food & Drink', aliases: ['cutlery'] },

  // Activities
  { emoji: '⚽', description: 'soccer ball', category: 'Activities', aliases: ['football', 'sport'] },
  { emoji: '🏀', description: 'basketball', category: 'Activities', aliases: ['sport'] },
  { emoji: '🏈', description: 'american football', category: 'Activities', aliases: ['sport'] },
  { emoji: '⚾', description: 'baseball', category: 'Activities', aliases: ['sport'] },
  { emoji: '🥎', description: 'softball', category: 'Activities', aliases: ['sport'] },
  { emoji: '🎾', description: 'tennis', category: 'Activities', aliases: ['sport'] },
  { emoji: '🏐', description: 'volleyball', category: 'Activities', aliases: ['sport'] },
  { emoji: '🏉', description: 'rugby football', category: 'Activities', aliases: ['sport'] },
  { emoji: '🎱', description: 'pool 8 ball', category: 'Activities', aliases: ['billiards', 'game'] },
  { emoji: '🏓', description: 'ping pong', category: 'Activities', aliases: ['table tennis'] },
  { emoji: '🏸', description: 'badminton', category: 'Activities', aliases: ['sport'] },
  { emoji: '🏒', description: 'ice hockey', category: 'Activities', aliases: ['sport'] },
  { emoji: '🏑', description: 'field hockey', category: 'Activities', aliases: ['sport'] },
  { emoji: '🏏', description: 'cricket game', category: 'Activities', aliases: ['sport'] },
  { emoji: '🥅', description: 'goal net', category: 'Activities', aliases: ['sport'] },
  { emoji: '⛳', description: 'flag in hole', category: 'Activities', aliases: ['golf'] },
  { emoji: '🏹', description: 'bow and arrow', category: 'Activities', aliases: ['archery'] },
  { emoji: '🎣', description: 'fishing pole', category: 'Activities', aliases: ['fish'] },
  { emoji: '🥊', description: 'boxing glove', category: 'Activities', aliases: ['fight'] },
  { emoji: '🥋', description: 'martial arts uniform', category: 'Activities', aliases: ['judo', 'karate'] },
  { emoji: '⛸️', description: 'ice skate', category: 'Activities', aliases: ['skating'] },
  { emoji: '🎿', description: 'skis', category: 'Activities', aliases: ['skiing'] },
  { emoji: '⛷️', description: 'skier', category: 'Activities', aliases: ['skiing'] },
  { emoji: '🏂', description: 'snowboarder', category: 'Activities', aliases: ['skiing'] },
  { emoji: '🏋️', description: 'person lifting weights', category: 'Activities', aliases: ['gym', 'workout'] },
  { emoji: '🤸', description: 'person cartwheeling', category: 'Activities', aliases: ['gymnastics'] },
  { emoji: '🤺', description: 'person fencing', category: 'Activities', aliases: ['sport'] },
  { emoji: '🏇', description: 'horse racing', category: 'Activities', aliases: ['race'] },
  { emoji: '🏊', description: 'person swimming', category: 'Activities', aliases: ['swim'] },
  { emoji: '🏄', description: 'person surfing', category: 'Activities', aliases: ['surfer'] },
  { emoji: '🎯', description: 'bullseye', category: 'Activities', aliases: ['darts', 'target'] },
  { emoji: '🎳', description: 'bowling', category: 'Activities', aliases: ['game'] },
  { emoji: '🎮', description: 'video game', category: 'Activities', aliases: ['gaming', 'controller'] },
  { emoji: '🎲', description: 'game die', category: 'Activities', aliases: ['dice', 'gambling'] },
  { emoji: '🧩', description: 'puzzle piece', category: 'Activities', aliases: ['jigsaw'] },
  { emoji: '♟️', description: 'chess pawn', category: 'Activities', aliases: ['game'] },
  { emoji: '🎨', description: 'artist palette', category: 'Activities', aliases: ['painting', 'art'] },
  { emoji: '🎬', description: 'clapper board', category: 'Activities', aliases: ['movie', 'film'] },
  { emoji: '🎤', description: 'microphone', category: 'Activities', aliases: ['singing', 'karaoke'] },
  { emoji: '🎧', description: 'headphone', category: 'Activities', aliases: ['music', 'audio'] },
  { emoji: '🎷', description: 'saxophone', category: 'Activities', aliases: ['music'] },
  { emoji: '🎺', description: 'trumpet', category: 'Activities', aliases: ['music', 'instrument'] },
  { emoji: '🎸', description: 'guitar', category: 'Activities', aliases: ['music', 'instrument'] },
  { emoji: '🎹', description: 'musical keyboard', category: 'Activities', aliases: ['piano'] },
  { emoji: '🥁', description: 'drum', category: 'Activities', aliases: ['music'] },
  { emoji: '🎉', description: 'party popper', category: 'Activities', aliases: ['celebration', 'tada'] },
  { emoji: '🎊', description: 'confetti ball', category: 'Activities', aliases: ['celebration'] },
  { emoji: '🎄', description: 'Christmas tree', category: 'Activities', aliases: ['holiday'] },
  { emoji: '🎆', description: 'fireworks', category: 'Activities', aliases: ['celebration'] },

  // Travel & Places
  { emoji: '🚀', description: 'rocket', category: 'Travel & Places', aliases: ['space', 'launch'] },
  { emoji: '✈️', description: 'airplane', category: 'Travel & Places', aliases: ['flight', 'travel'] },
  { emoji: '🚁', description: 'helicopter', category: 'Travel & Places', aliases: ['chopper'] },
  { emoji: '🛰️', description: 'satellite', category: 'Travel & Places', aliases: ['space'] },
  { emoji: '🛸', description: 'flying saucer', category: 'Travel & Places', aliases: ['ufo'] },
  { emoji: '⛵', description: 'sailboat', category: 'Travel & Places', aliases: ['boat'] },
  { emoji: '🚢', description: 'ship', category: 'Travel & Places', aliases: ['boat', 'cruise'] },
  { emoji: '🚗', description: 'car', category: 'Travel & Places', aliases: ['vehicle'] },
  { emoji: '🚕', description: 'taxi', category: 'Travel & Places', aliases: ['cab'] },
  { emoji: '🚌', description: 'bus', category: 'Travel & Places', aliases: ['vehicle'] },
  { emoji: '🚓', description: 'police car', category: 'Travel & Places', aliases: ['cop'] },
  { emoji: '🚑', description: 'ambulance', category: 'Travel & Places', aliases: ['emergency'] },
  { emoji: '🚒', description: 'fire engine', category: 'Travel & Places', aliases: ['truck'] },
  { emoji: '🚚', description: 'delivery truck', category: 'Travel & Places', aliases: ['lorry'] },
  { emoji: '🚜', description: 'tractor', category: 'Travel & Places', aliases: ['farm'] },
  { emoji: '🚂', description: 'locomotive', category: 'Travel & Places', aliases: ['train', 'steam'] },
  { emoji: '🚲', description: 'bicycle', category: 'Travel & Places', aliases: ['bike', 'pedal'] },
  { emoji: '🛴', description: 'kick scooter', category: 'Travel & Places', aliases: ['scooter'] },
  { emoji: '🚦', description: 'vertical traffic light', category: 'Travel & Places', aliases: ['signal'] },
  { emoji: '🚧', description: 'construction', category: 'Travel & Places', aliases: ['work'] },
  { emoji: '🗽', description: 'statue of liberty', category: 'Travel & Places', aliases: ['new york', 'usa'] },
  { emoji: '🗼', description: 'tokyo tower', category: 'Travel & Places', aliases: ['japan', 'tower'] },
  { emoji: '🏰', description: 'castle', category: 'Travel & Places', aliases: ['disney', 'fortress'] },
  { emoji: '🏯', description: 'Japanese castle', category: 'Travel & Places', aliases: ['japan'] },
  { emoji: '🏟️', description: 'stadium', category: 'Travel & Places', aliases: ['arena'] },
  { emoji: '🎡', description: 'ferris wheel', category: 'Travel & Places', aliases: ['amusement park'] },
  { emoji: '🎢', description: 'roller coaster', category: 'Travel & Places', aliases: ['amusement park'] },
  { emoji: '🎪', description: 'circus tent', category: 'Travel & Places', aliases: ['party'] },
  { emoji: '⛺', description: 'tent', category: 'Travel & Places', aliases: ['camping', 'outdoors'] },
  { emoji: '🏠', description: 'house', category: 'Travel & Places', aliases: ['home', 'building'] },
  { emoji: '🏡', description: 'house with garden', category: 'Travel & Places', aliases: ['home'] },
  { emoji: '🏢', description: 'office building', category: 'Travel & Places', aliases: ['work'] },
  { emoji: '🏨', description: 'hotel', category: 'Travel & Places', aliases: ['building'] },
  { emoji: '🏦', description: 'bank', category: 'Travel & Places', aliases: ['money'] },
  { emoji: '🏥', description: 'hospital', category: 'Travel & Places', aliases: ['doctor'] },
  { emoji: '🏪', description: 'convenience store', category: 'Travel & Places', aliases: ['shop'] },
  { emoji: '🏫', description: 'school', category: 'Travel & Places', aliases: ['learn'] },
  { emoji: '🏭', description: 'factory', category: 'Travel & Places', aliases: ['industry'] },
  { emoji: '🏛️', description: 'classical building', category: 'Travel & Places', aliases: ['court'] },
  { emoji: '🏜️', description: 'desert', category: 'Travel & Places', aliases: ['sand'] },
  { emoji: '🏝️', description: 'desert island', category: 'Travel & Places', aliases: ['beach', 'tropical'] },
  { emoji: '🏞️', description: 'national park', category: 'Travel & Places', aliases: ['nature'] },
  { emoji: '⛰️', description: 'mountain', category: 'Travel & Places', aliases: ['hike'] },

  // Objects
  { emoji: '💡', description: 'light bulb', category: 'Objects', aliases: ['idea', 'electric'] },
  { emoji: '💻', description: 'laptop', category: 'Objects', aliases: ['computer', 'tech'] },
  { emoji: '🖥️', description: 'desktop computer', category: 'Objects', aliases: ['tech'] },
  { emoji: '🖱️', description: 'computer mouse', category: 'Objects', aliases: ['tech'] },
  { emoji: '📱', description: 'mobile phone', category: 'Objects', aliases: ['iphone', 'cell'] },
  { emoji: '☎️', description: 'telephone', category: 'Objects', aliases: ['phone'] },
  { emoji: '📺', description: 'television', category: 'Objects', aliases: ['tv', 'program'] },
  { emoji: '📷', description: 'camera', category: 'Objects', aliases: ['photo', 'photography'] },
  { emoji: '📹', description: 'video camera', category: 'Objects', aliases: ['film'] },
  { emoji: '🎥', description: 'movie camera', category: 'Objects', aliases: ['film'] },
  { emoji: '📽️', description: 'film projector', category: 'Objects', aliases: ['movie'] },
  { emoji: '📼', description: 'videocassette', category: 'Objects', aliases: ['vhs'] },
  { emoji: '💿', description: 'optical disk', category: 'Objects', aliases: ['cd', 'dvd'] },
  { emoji: '💾', description: 'floppy disk', category: 'Objects', aliases: ['save'] },
  { emoji: '💰', description: 'money bag', category: 'Objects', aliases: ['dollar', 'cash'] },
  { emoji: '💵', description: 'dollar banknote', category: 'Objects', aliases: ['money'] },
  { emoji: '💴', description: 'yen banknote', category: 'Objects', aliases: ['money'] },
  { emoji: '💶', description: 'euro banknote', category: 'Objects', aliases: ['money'] },
  { emoji: '💷', description: 'pound banknote', category: 'Objects', aliases: ['money'] },
  { emoji: '💎', description: 'gem stone', category: 'Objects', aliases: ['diamond', 'rich'] },
  { emoji: '🔧', description: 'wrench', category: 'Objects', aliases: ['tool', 'fix'] },
  { emoji: '🔨', description: 'hammer', category: 'Objects', aliases: ['tool'] },
  { emoji: '🛠️', description: 'hammer and wrench', category: 'Objects', aliases: ['tools'] },
  { emoji: '🔑', description: 'key', category: 'Objects', aliases: ['lock', 'password'] },
  { emoji: '🚪', description: 'door', category: 'Objects', aliases: ['exit'] },
  { emoji: '🪑', description: 'chair', category: 'Objects', aliases: ['seat'] },
  { emoji: '🛏️', description: 'bed', category: 'Objects', aliases: ['sleep'] },
  { emoji: '🛁', description: 'bathtub', category: 'Objects', aliases: ['clean'] },
  { emoji: '🚽', description: 'toilet', category: 'Objects', aliases: ['wc'] },
  { emoji: '🎁', description: 'wrapped gift', category: 'Objects', aliases: ['present', 'birthday'] },
  { emoji: '🎈', description: 'balloon', category: 'Objects', aliases: ['party', 'celebration'] },
  { emoji: '📚', description: 'books', category: 'Objects', aliases: ['library', 'reading'] },
  { emoji: '📖', description: 'open book', category: 'Objects', aliases: ['read'] },
  { emoji: '📜', description: 'scroll', category: 'Objects', aliases: ['document'] },
  { emoji: '📄', description: 'page with curl', category: 'Objects', aliases: ['document'] },
  { emoji: '📰', description: 'newspaper', category: 'Objects', aliases: ['news'] },
  { emoji: '🔗', description: 'link', category: 'Objects', aliases: ['url'] },
  { emoji: '📎', description: 'paperclip', category: 'Objects', aliases: ['attachment'] },
  { emoji: '✂️', description: 'scissors', category: 'Objects', aliases: ['cut'] },
  { emoji: '🗑️', description: 'wastebasket', category: 'Objects', aliases: ['trash'] },
  { emoji: '🔒', description: 'locked', category: 'Objects', aliases: ['secure'] },
  { emoji: '🔓', description: 'unlocked', category: 'Objects', aliases: ['secure'] },
  { emoji: '🔔', description: 'bell', category: 'Objects', aliases: ['notification'] },
  { emoji: '🚬', description: 'cigarette', category: 'Objects', aliases: ['smoke'] },
  { emoji: '💣', description: 'bomb', category: 'Objects', aliases: ['explode'] },
  { emoji: '🔫', description: 'pistol', category: 'Objects', aliases: ['gun'] },

  // Symbols
  { emoji: '❤️', description: 'red heart', category: 'Symbols', aliases: ['love'] },
  { emoji: '🧡', description: 'orange heart', category: 'Symbols', aliases: ['love'] },
  { emoji: '💛', description: 'yellow heart', category: 'Symbols', aliases: ['love'] },
  { emoji: '💚', description: 'green heart', category: 'Symbols', aliases: ['love'] },
  { emoji: '💙', description: 'blue heart', category: 'Symbols', aliases: ['love'] },
  { emoji: '💜', description: 'purple heart', category: 'Symbols', aliases: ['love'] },
  { emoji: '🖤', description: 'black heart', category: 'Symbols', aliases: ['love'] },
  { emoji: '🤍', description: 'white heart', category: 'Symbols', aliases: ['love'] },
  { emoji: '🤎', description: 'brown heart', category: 'Symbols', aliases: ['love'] },
  { emoji: '💔', description: 'broken heart', category: 'Symbols', aliases: ['sad', 'breakup'] },
  { emoji: '❣️', description: 'heart exclamation', category: 'Symbols', aliases: ['love'] },
  { emoji: '💕', description: 'two hearts', category: 'Symbols', aliases: ['love'] },
  { emoji: '💞', description: 'revolving hearts', category: 'Symbols', aliases: ['love'] },
  { emoji: '💓', description: 'beating heart', category: 'Symbols', aliases: ['love'] },
  { emoji: '💗', description: 'growing heart', category: 'Symbols', aliases: ['love'] },
  { emoji: '💖', description: 'sparkling heart', category: 'Symbols', aliases: ['love'] },
  { emoji: '💘', description: 'heart with arrow', category: 'Symbols', aliases: ['cupid', 'love'] },
  { emoji: '💝', description: 'heart with ribbon', category: 'Symbols', aliases: ['gift', 'love'] },
  { emoji: '💟', description: 'heart decoration', category: 'Symbols', aliases: ['love'] },
  { emoji: '☮️', description: 'peace symbol', category: 'Symbols', aliases: ['peace'] },
  { emoji: '✝️', description: 'latin cross', category: 'Symbols', aliases: ['christian'] },
  { emoji: '☪️', description: 'star and crescent', category: 'Symbols', aliases: ['islam'] },
  { emoji: '🕉️', description: 'om', category: 'Symbols', aliases: ['hindu'] },
  { emoji: '☸️', description: 'wheel of dharma', category: 'Symbols', aliases: ['buddhist'] },
  { emoji: '✡️', description: 'star of David', category: 'Symbols', aliases: ['jewish'] },
  { emoji: '🔯', description: 'dotted six-pointed star', category: 'Symbols', aliases: ['religion'] },
  { emoji: '🕎', description: 'menorah', category: 'Symbols', aliases: ['hanukkah'] },
  { emoji: '☯️', description: 'yin yang', category: 'Symbols', aliases: ['balance'] },
  { emoji: '☦️', description: 'orthodox cross', category: 'Symbols', aliases: ['christian'] },
  { emoji: '🛐', description: 'place of worship', category: 'Symbols', aliases: ['religion'] },
  { emoji: '⛎', description: 'Ophiuchus', category: 'Symbols', aliases: ['zodiac'] },
  { emoji: '♈', description: 'Aries', category: 'Symbols', aliases: ['zodiac'] },
  { emoji: '♉', description: 'Taurus', category: 'Symbols', aliases: ['zodiac'] },
  { emoji: '♊', description: 'Gemini', category: 'Symbols', aliases: ['zodiac'] },
  { emoji: '♋', description: 'Cancer', category: 'Symbols', aliases: ['zodiac'] },
  { emoji: '♌', description: 'Leo', category: 'Symbols', aliases: ['zodiac'] },
  { emoji: '♍', description: 'Virgo', category: 'Symbols', aliases: ['zodiac'] },
  { emoji: '♎', description: 'Libra', category: 'Symbols', aliases: ['zodiac'] },
  { emoji: '♏', description: 'Scorpio', category: 'Symbols', aliases: ['zodiac'] },
  { emoji: '♐', description: 'Sagittarius', category: 'Symbols', aliases: ['zodiac'] },
  { emoji: '♑', description: 'Capricorn', category: 'Symbols', aliases: ['zodiac'] },
  { emoji: '♒', description: 'Aquarius', category: 'Symbols', aliases: ['zodiac'] },
  { emoji: '♓', description: 'Pisces', category: 'Symbols', aliases: ['zodiac'] },
  { emoji: '🆔', description: 'ID button', category: 'Symbols', aliases: ['identity'] },
  { emoji: '⚛️', description: 'atom symbol', category: 'Symbols', aliases: ['science'] },
  { emoji: '🉑', description: 'Japanese “acceptable” button', category: 'Symbols', aliases: ['ok'] },
  { emoji: '☢️', description: 'radioactive', category: 'Symbols', aliases: ['danger'] },
  { emoji: '☣️', description: 'biohazard', category: 'Symbols', aliases: ['danger'] },
  { emoji: '📴', description: 'mobile phone off', category: 'Symbols', aliases: ['silent'] },
  { emoji: '📳', description: 'vibration mode', category: 'Symbols', aliases: ['phone'] },
  { emoji: '🈶', description: 'Japanese “not free of charge” button', category: 'Symbols', aliases: ['paid'] },
  { emoji: '🈚', description: 'Japanese “free of charge” button', category: 'Symbols', aliases: ['free'] },
  { emoji: '🈺', description: 'Japanese “open for business” button', category: 'Symbols', aliases: ['open'] },
  { emoji: '🈷️', description: 'Japanese “monthly amount” button', category: 'Symbols', aliases: ['month'] },
  { emoji: '🆚', description: 'VS button', category: 'Symbols', aliases: ['versus'] },
  { emoji: '💯', description: 'hundred points', category: 'Symbols', aliases: ['perfect', 'score'] },
  { emoji: '✅', description: 'check mark button', category: 'Symbols', aliases: ['done', 'agree'] },
  { emoji: '❌', description: 'cross mark', category: 'Symbols', aliases: ['no', 'wrong'] },
  { emoji: '❓', description: 'question mark', category: 'Symbols', aliases: ['help', 'doubt'] },
  { emoji: '❔', description: 'white question mark', category: 'Symbols', aliases: ['help'] },
  { emoji: '❕', description: 'white exclamation mark', category: 'Symbols', aliases: ['surprise'] },
  { emoji: '❗', description: 'exclamation mark', category: 'Symbols', aliases: ['surprise', 'wow'] },
  { emoji: '©️', description: 'copyright', category: 'Symbols', aliases: ['c'] },
  { emoji: '®️', description: 'registered', category: 'Symbols', aliases: ['r'] },
  { emoji: '™️', description: 'trade mark', category: 'Symbols', aliases: ['tm'] },
];