import React from 'react';

export const Terms: React.FC = () => {
    return (
        <div className="max-w-4xl mx-auto space-y-8">
            <div className="bg-white dark:bg-gray-800 p-8 rounded-xl shadow-md">
                <h2 className="text-3xl font-bold text-gray-900 dark:text-white">Terms of Service & Fair Use Policy</h2>
                <p className="text-sm text-gray-500 dark:text-gray-400 mt-2">Last updated: September 3, 2024</p>

                <div className="mt-6 prose prose-lg dark:prose-invert max-w-none text-gray-700 dark:text-gray-300">
                    <p>Welcome to EngageSuite.ai. Our goal is to provide a powerful and sustainable AI toolkit to help you grow. This Fair Use Policy outlines the usage limits for our AI generation features to ensure service quality and prevent abuse for all our users. By using our service, you agree to these terms.</p>

                    <h3 className="text-xl font-bold text-gray-900 dark:text-white mt-8 mb-2">1. AI Generation Services</h3>
                    <p>
                        EngageSuite.ai offers advanced AI-powered media generation tools, including Image, Video, and Voice creation. These features are computationally intensive. This policy ensures we can offer them sustainably. A "generation" is defined as one successful creation request sent to the AI model.
                    </p>

                    <h3 className="text-xl font-bold text-gray-900 dark:text-white mt-8 mb-2">2. Subscription Plans and Pricing</h3>
                    <p>
                        Our pricing is available on our website's pricing section. All prices are listed in USD. The Agency plan is offered on a custom basis for users with extensive needs, and interested parties should contact our sales team for a quote. We reserve the right to change our pricing at any time, with notice provided to existing subscribers.
                    </p>
                    
                    <h3 className="text-xl font-bold text-gray-900 dark:text-white mt-8 mb-2">3. AI Autopilot Feature</h3>
                    <p>
                        AI Autopilot is a premium add-on feature available for purchase on any paid plan. It automates the entire content creation workflow, from strategy to final post generation.
                    </p>
                     <ul>
                        <li><strong>Functionality:</strong> When you launch a campaign, Autopilot first generates a content strategy. It then proceeds to create individual posts based on this plan, which includes generating a unique AI image and multiple AI caption suggestions for each post.</li>
                        <li><strong>Credit Consumption:</strong> Each post created by an Autopilot campaign will consume credits from your monthly allowance, typically <strong>1 Image Generation credit</strong> and <strong>1 Caption Generation credit</strong> per post.</li>
                        <li><strong>Approval Process:</strong> All content generated by Autopilot is automatically placed into your "Approval Workflow" queue with a 'Draft' status. No content will be published without your explicit review and approval. You retain full control over your brand's voice and output.</li>
                    </ul>


                    <h3 className="text-xl font-bold text-gray-900 dark:text-white mt-8 mb-2">4. Fair Use Policy & Monthly Allowances</h3>
                    <p>
                        Different subscription plans come with different allowances for AI generation. These are designed to provide ample creative freedom while maintaining service stability.
                    </p>
                    
                    <h4>Media Storage Allowance</h4>
                     <p>
                        Users can upload their own media (images and videos) for use in features like the AI Caption Generator. Each plan comes with a specific storage limit:
                    </p>
                    <ul>
                        <li><strong>Free Plan:</strong> 100 MB of media storage.</li>
                        <li><strong>Pro Plan:</strong> 1 GB of media storage.</li>
                        <li><strong>Elite Plan:</strong> 10 GB of media storage.</li>
                        <li><strong>Agency Plan:</strong> 50 GB of media storage.</li>
                    </ul>

                    <h4>AI Image Generation</h4>
                     <ul>
                        <li><strong>Pro Plan:</strong> <strong>50</strong> AI Image Generations per month.</li>
                        <li><strong>Elite Plan:</strong> <strong>500</strong> AI Image Generations per month.</li>
                        <li><strong>Agency Plan:</strong> Includes <strong>"Unlimited*" AI Image Generations</strong>. This is subject to a fair use policy intended to prevent abuse such as automated scripting or reselling. We reserve the right to monitor usage and may temporarily throttle or contact users exhibiting usage patterns indicative of abuse.</li>
                    </ul>

                    <h4>AI Video Generation (Veo)</h4>
                    <p>
                        Due to the high computational cost of video generation, plans include a specific number of monthly video generation credits:
                    </p>
                    <ul>
                        <li><strong>Pro Plan:</strong> <strong>1</strong> AI Video Generation per month.</li>
                        <li><strong>Elite Plan:</strong> <strong>25</strong> AI Video Generations per month.</li>
                        <li><strong>Agency Plan:</strong> <strong>50</strong> AI Video Generations per month.</li>
                    </ul>
                    <p>
                        Credits reset on your monthly billing date. Unused credits do not roll over to the next month.
                    </p>
                    <p className="font-semibold mt-2">Director Mode & Multi-Clip Videos:</p>
                    <p>
                        The "Director Mode" feature allows you to create videos composed of multiple scenes. Each scene generated counts as <strong>1 Video Credit</strong>. For example, generating a video with 3 scenes will consume 3 credits from your monthly allowance.
                    </p>

                    <h4>AI Voice-overs & Custom Voice Cloning</h4>
                    <p>
                        This premium feature allows you to upload voice samples to create AI voice clones. By uploading a sample, you affirm that you have all necessary rights to use that voice. Plan limits for stored custom voices are as follows:
                    </p>
                    <ul>
                        <li><strong>Pro Plan:</strong> <strong>1</strong> Custom Voice Clone.</li>
                        <li><strong>Elite Plan:</strong> <strong>3</strong> Custom Voice Clones.</li>
                        <li><strong>Agency Plan:</strong> <strong>Unlimited*</strong> Custom Voice Clones. This is subject to our Fair Use Policy to prevent system abuse.</li>
                    </ul>


                    <h4>Automation Workflows</h4>
                    <p>
                        The number of active automation workflows is limited by plan to ensure system stability:
                    </p>
                     <ul>
                        <li><strong>Pro Plan:</strong> 2 active workflows.</li>
                        <li><strong>Elite Plan:</strong> 10 active workflows.</li>
                        <li><strong>Agency Plan:</strong> Unlimited active workflows.</li>
                    </ul>
                    <p>Workflows may not be used for spamming, harassment, or any purpose that violates our Prohibited Content policy.</p>

                     <h4>AI Avatar (Base Image)</h4>
                    <p>
                        This feature, available on Elite and Agency plans, allows you to upload a base image for use in AI generations. You must own the rights to any image you upload and are responsible for all content created using it.
                    </p>

                    <div className="mt-8 p-6 border-l-4 border-yellow-400 bg-yellow-50 dark:bg-yellow-900/30 rounded-r-lg">
                        <h4 className="text-xl font-bold text-yellow-800 dark:text-yellow-200">Important: Policy on Client Usage (Elite & Agency Plans)</h4>
                        <p className="mt-2 text-yellow-900 dark:text-yellow-100">
                           The monthly allowances for all AI generation features are allocated to the <strong>primary subscriber's account only</strong>. These allowances are intended to be used across all managed clients and are <strong>not provided on a per-client basis.</strong>
                        </p>
                        <p className="mt-2 text-yellow-900 dark:text-yellow-100">
                            <strong>Example:</strong> An Agency subscriber managing 10 clients has a total monthly allowance of 50 video generations to use for any of their clients' needs. It is not an allowance of 50 video generations for <em>each</em> of the 10 clients.
                        </p>
                    </div>

                    <h3 className="text-xl font-bold text-gray-900 dark:text-white mt-8 mb-2">5. Bring Your Own API Key (BYOK) Model</h3>
                    <p>
                        For users whose needs exceed the monthly video generation allowances, we offer a "Bring Your Own Key" (BYOK) model for Elite and Agency plans.
                    </p>
                    <ul>
                        <li><strong>Activation:</strong> Once you consume your monthly video generation credits, you can connect your own Google AI API key to continue using the service without interruption.</li>
                        <li><strong>Billing:</strong> All generation requests made using your own key will be billed directly to your Google Cloud account at their standard rates. EngageSuite.ai will not charge you for this usage.</li>
                        <li><strong>Your Responsibility:</strong> You are solely responsible for all costs and usage associated with your own API key. We highly recommend setting up budget alerts and monitoring your usage within your Google Cloud dashboard.</li>
                        <li><strong>More Information:</strong> To understand Google AI's pricing structure, please refer to their official <a href="https://ai.google.dev/gemini-api/docs/billing" target="_blank" rel="noopener noreferrer" className="text-primary-500 hover:underline">billing documentation</a>.</li>
                    </ul>

                    <h3 className="text-xl font-bold text-gray-900 dark:text-white mt-8 mb-2">6. One-Time Credit Packs</h3>
                    <p>
                        For users on Pro, Elite, and Agency plans, we offer one-time credit packs for purchase if you exhaust your monthly generation allowances.
                    </p>
                    <ul>
                        <li><strong>Nature of Purchase:</strong> Credit packs are a one-time, non-recurring purchase.</li>
                        <li><strong>Usage Priority:</strong> Purchased credits are only consumed after your monthly plan's allowance for the current billing cycle has been fully used.</li>
                        <li><strong>Expiration:</strong> Purchased credits do not expire and will remain on your account until they are used.</li>
                        <li><strong>Refunds:</strong> All purchases of one-time credit packs are final and non-refundable.</li>
                    </ul>

                    <h3 className="text-xl font-bold text-gray-900 dark:text-white mt-8 mb-2">7. Prohibited Content & Use</h3>
                    <p>
                        You may not use EngageSuite.ai to create, upload, or share any content that is illegal, harmful, fraudulent, deceptive, infringes on any third party's rights, constitutes hate speech, or promotes self-harm. Violating this policy may result in immediate account suspension or termination.
                    </p>

                    <h3 className="text-xl font-bold text-gray-900 dark:text-white mt-8 mb-2">8. Changes to This Policy</h3>
                    <p>
                        We may update this Fair Use Policy from time to time. If we make any changes, we will notify you by revising the "Last updated" date at the top of this policy and, in some cases, we may provide you with additional notice.
                    </p>
                </div>
            </div>
        </div>
    );
};
