import type { CreatorIdentityQuestion } from './types.js';

export const CREATOR_IDENTITY_PROMISE =
  "Let's figure out what people are really drawn to you for — and what they'll pay you for.";

export const CREATOR_IDENTITY_QUESTIONS: CreatorIdentityQuestion[] = [
  {
    id: 'q1',
    section: 1,
    sectionTitle: 'Audience Pull',
    prompt: 'What do people usually notice about you first?',
    type: 'single_select',
    options: [
      { id: 'looks_visual', label: 'My on-camera presence or how I show up visually' },
      { id: 'personality', label: 'My personality' },
      { id: 'energy_confidence', label: 'My energy or confidence' },
      { id: 'humor', label: 'My humor' },
      { id: 'knowledge_advice', label: 'My knowledge or advice' },
      { id: 'lifestyle', label: 'My lifestyle' },
      { id: 'creativity', label: 'My creativity' },
      { id: 'talent_skill', label: 'My talent or skill' },
      { id: 'exclusivity_mystery', label: 'My exclusivity or mystery' },
      { id: 'relatability', label: 'My relatability' },
      { id: 'other', label: 'Other' },
    ],
  },
  {
    id: 'q2',
    section: 1,
    sectionTitle: 'Audience Pull',
    prompt: 'Why do people keep coming back to your content?',
    type: 'multi_select',
    maxSelections: 3,
    options: [
      { id: 'connected', label: 'They feel connected to me' },
      { id: 'updates_style', label: 'They like my updates and content style' },
      { id: 'want_access', label: 'They want more access to me' },
      { id: 'entertained', label: 'They are entertained by me' },
      { id: 'learn', label: 'They learn from me' },
      { id: 'aesthetic', label: 'The overall vibe or look of my content (mood, not only beauty)' },
      { id: 'curious_life', label: 'They are curious about my life' },
      { id: 'exclusive_content', label: 'They enjoy my exclusive or premium content' },
      { id: 'talk_to_me', label: 'They like talking to me' },
      { id: 'inspired', label: 'They feel inspired by me' },
      { id: 'other', label: 'Other' },
    ],
  },
  {
    id: 'q3',
    section: 1,
    sectionTitle: 'Audience Pull',
    prompt: 'What do followers most often message or comment about?',
    type: 'multi_select',
    options: [
      { id: 'appearance', label: 'My appearance' },
      { id: 'confidence', label: 'My confidence' },
      { id: 'personality', label: 'My personality' },
      { id: 'advice', label: 'My advice' },
      { id: 'lifestyle', label: 'My lifestyle' },
      { id: 'energy', label: 'My energy' },
      { id: 'content_style', label: 'My content style' },
      { id: 'want_access', label: 'Wanting more access to me' },
      { id: 'personal_interaction', label: 'Asking for more personal interaction' },
      { id: 'exclusive_content', label: 'Wanting exclusive content' },
      { id: 'other', label: 'Other' },
    ],
  },
  {
    id: 'q4',
    section: 2,
    sectionTitle: 'Natural Content Lane',
    prompt: 'What kind of content feels most natural for you to create?',
    type: 'multi_select',
    maxSelections: 4,
    options: [
      { id: 'selfies', label: 'Selfies and aesthetic photos' },
      { id: 'bts', label: 'Behind-the-scenes moments' },
      { id: 'talking_cam', label: 'Talking to camera' },
      { id: 'tutorials', label: 'Tutorials or how-to content' },
      { id: 'daily_life', label: 'Daily life updates' },
      { id: 'storytimes', label: 'Storytimes' },
      { id: 'motivational', label: 'Motivational or confidence content' },
      { id: 'playful_tease', label: 'Playful or teasing content' },
      { id: 'reactions', label: 'Reactions or commentary' },
      { id: 'personal_updates', label: 'Personal updates' },
      { id: 'premium_access_style', label: 'Premium access style content' },
      { id: 'community', label: 'Community-style interaction' },
      { id: 'other', label: 'Other' },
    ],
  },
  {
    id: 'q5',
    section: 2,
    sectionTitle: 'Natural Content Lane',
    prompt: 'Which content lane feels closest to your main niche? (rank top 3)',
    type: 'ranked_select',
    rankTop: 3,
    options: [
      { id: 'lifestyle', label: 'Lifestyle' },
      { id: 'beauty', label: 'Beauty' },
      { id: 'fashion', label: 'Fashion' },
      { id: 'fitness', label: 'Fitness' },
      { id: 'wellness', label: 'Wellness' },
      { id: 'dating_flirt', label: 'Dating / flirt energy' },
      { id: 'soft_luxury', label: 'Soft luxury' },
      { id: 'personal_access', label: 'Personal access' },
      { id: 'entertainment', label: 'Entertainment' },
      { id: 'advice_coaching', label: 'Advice / coaching' },
      { id: 'humor_personality', label: 'Humor / personality' },
      { id: 'music_performance', label: 'Music / performance' },
      { id: 'art_creativity', label: 'Art / creativity' },
      { id: 'gaming', label: 'Gaming' },
      { id: 'travel', label: 'Travel' },
      { id: 'niche_hobby', label: 'Niche hobby or interest' },
      { id: 'community_connection', label: 'Community / connection' },
      { id: 'other', label: 'Other' },
    ],
  },
  {
    id: 'q6',
    section: 3,
    sectionTitle: 'Brand Identity',
    prompt: 'Which 3 words feel most like your brand?',
    type: 'multi_select',
    exactSelections: 3,
    options: [
      { id: 'bold', label: 'Bold' },
      { id: 'soft', label: 'Soft' },
      { id: 'playful', label: 'Playful' },
      { id: 'flirty', label: 'Flirty' },
      { id: 'polished', label: 'Polished' },
      { id: 'luxury', label: 'Luxury' },
      { id: 'confident', label: 'Confident' },
      { id: 'relatable', label: 'Relatable' },
      { id: 'mysterious', label: 'Mysterious' },
      { id: 'classy', label: 'Classy' },
      { id: 'funny', label: 'Funny' },
      { id: 'smart', label: 'Smart' },
      { id: 'sensual', label: 'Sensual' },
      { id: 'energetic', label: 'Energetic' },
      { id: 'calm', label: 'Calm' },
      { id: 'exclusive', label: 'Exclusive' },
      { id: 'down_to_earth', label: 'Down-to-earth' },
      { id: 'edgy', label: 'Edgy' },
      { id: 'warm', label: 'Warm' },
      { id: 'other', label: 'Other' },
    ],
  },
  {
    id: 'q7',
    section: 3,
    sectionTitle: 'Brand Identity',
    prompt: 'How do you naturally show up online?',
    type: 'single_select',
    options: [
      { id: 'polished', label: 'Polished and curated' },
      { id: 'casual', label: 'Casual and spontaneous' },
      { id: 'intimate', label: 'Personal and intimate' },
      { id: 'bold_attention', label: 'Bold and attention-grabbing' },
      { id: 'funny_chaotic', label: 'Funny and chaotic' },
      { id: 'helpful', label: 'Helpful and informative' },
      { id: 'reserved_intrigue', label: 'Reserved but intriguing' },
      { id: 'premium_exclusive', label: 'Premium and exclusive' },
      { id: 'community_interactive', label: 'Community-first and interactive' },
      { id: 'other', label: 'Other' },
    ],
  },
  {
    id: 'q8',
    section: 3,
    sectionTitle: 'Brand Identity',
    prompt: 'What do you want people to feel when they experience your brand?',
    type: 'multi_select',
    maxSelections: 3,
    options: [
      { id: 'closer', label: 'Closer to me' },
      { id: 'inspired', label: 'Inspired' },
      { id: 'attracted', label: 'Attracted' },
      { id: 'entertained', label: 'Entertained' },
      { id: 'comfortable', label: 'Comfortable' },
      { id: 'curious', label: 'Curious' },
      { id: 'motivated', label: 'Motivated' },
      { id: 'excited', label: 'Excited' },
      { id: 'seen', label: 'Seen and connected' },
      { id: 'exclusive_group', label: 'Like they are part of something exclusive' },
      { id: 'other', label: 'Other' },
    ],
  },
  {
    id: 'q9',
    section: 4,
    sectionTitle: 'Monetization Fit',
    prompt: 'What do you think your audience wants most from you?',
    type: 'single_select',
    options: [
      { id: 'entertainment', label: 'Entertainment' },
      { id: 'connection', label: 'Connection' },
      { id: 'access', label: 'Access' },
      { id: 'exclusivity', label: 'Exclusivity' },
      { id: 'advice', label: 'Advice' },
      { id: 'motivation', label: 'Motivation' },
      { id: 'fantasy', label: 'Fantasy / escapism' },
      { id: 'community', label: 'Community' },
      { id: 'conversation', label: 'Conversation' },
      { id: 'style', label: 'Outfits, visuals, or style inspiration' },
      { id: 'other', label: 'Other' },
    ],
  },
  {
    id: 'q10',
    section: 4,
    sectionTitle: 'Monetization Fit',
    prompt: 'What would people be most likely to pay you for first? (rank top 3)',
    type: 'ranked_select',
    rankTop: 3,
    options: [
      { id: 'membership', label: 'Monthly membership' },
      { id: 'exclusive_posts', label: 'Exclusive posts' },
      { id: 'locked_content', label: 'Locked content' },
      { id: 'private_messages', label: 'Private messages' },
      { id: 'tips', label: 'Tips / direct support' },
      { id: 'one_on_one', label: '1:1 chats or sessions' },
      { id: 'shoutouts', label: 'Personalized shoutouts' },
      { id: 'bts', label: 'Behind-the-scenes access' },
      { id: 'bonus_drops', label: 'Bonus drops' },
      { id: 'community', label: 'Community access' },
      { id: 'coaching', label: 'Coaching / advice' },
      { id: 'custom', label: 'Custom requests' },
      { id: 'other', label: 'Other' },
    ],
  },
  {
    id: 'q11',
    section: 4,
    sectionTitle: 'Monetization Fit',
    prompt: 'Which offer feels easiest for you to start with?',
    type: 'single_select',
    options: [
      { id: 'membership', label: 'Membership' },
      { id: 'paid_posts', label: 'Paid posts' },
      { id: 'messages', label: 'Messages' },
      { id: 'tips', label: 'Tips' },
      { id: 'direct_support', label: 'Direct support' },
      { id: 'exclusive_updates', label: 'Exclusive updates' },
      { id: 'sessions', label: 'Sessions' },
      { id: 'community_access', label: 'Community access' },
      { id: 'shoutouts', label: 'Shoutouts' },
      { id: 'not_sure', label: "I'm not sure yet" },
      { id: 'other', label: 'Other' },
    ],
  },
  {
    id: 'q12',
    section: 5,
    sectionTitle: 'Clarity and Blockers',
    prompt: 'What is your biggest challenge right now?',
    type: 'single_select',
    options: [
      { id: 'no_niche', label: "I don't know my niche" },
      { id: 'no_brand', label: "I don't know my brand" },
      { id: 'not_different', label: "I don't know what makes me different" },
      { id: 'no_pay', label: "I don't know what fans would pay for" },
      { id: 'random_page', label: 'My page feels random' },
      { id: 'describe_hard', label: 'I struggle to describe myself' },
      { id: 'ideas_no_direction', label: 'I have ideas but no clear direction' },
      { id: 'tie_together', label: 'I need help tying everything together' },
      { id: 'other', label: 'Other' },
    ],
  },
  {
    id: 'q13',
    section: 5,
    sectionTitle: 'Clarity and Blockers',
    prompt: 'How clear are you on your creator identity right now?',
    type: 'scale',
    scaleMin: 1,
    scaleMax: 5,
    scaleLabels: {
      1: 'I have no idea',
      3: 'I have a rough sense',
      5: 'I know exactly who I am as a creator',
    },
  },
  {
    id: 'q14',
    section: 6,
    sectionTitle: 'Open Responses',
    prompt: 'If someone described your creator brand in one sentence, what would you want them to say?',
    type: 'long_text',
    required: true,
  },
  {
    id: 'q15',
    section: 6,
    sectionTitle: 'Open Responses',
    prompt: 'What kind of content do you genuinely enjoy making the most?',
    type: 'long_text',
    required: true,
  },
  {
    id: 'q16',
    section: 6,
    sectionTitle: 'Open Responses',
    prompt: "What do you think fans get from you that they can't get somewhere else?",
    type: 'long_text',
    required: true,
  },
  {
    id: 'q17',
    section: 6,
    sectionTitle: 'Open Responses',
    prompt: 'Tell us anything else about your niche, style, audience, or what you want your brand to become.',
    type: 'long_text',
    required: false,
  },
];

export function questionById(id: string): CreatorIdentityQuestion | undefined {
  return CREATOR_IDENTITY_QUESTIONS.find((q) => q.id === id);
}
