export const APP_KNOWLEDGE = `
# EchoFlux.AI Knowledge Base

## Core Concept
EchoFlux.AI is an AI Social & Marketing Operating System. It offers two tailored experiences: one for "Creators" focused on brand growth and engagement, and one for "Businesses" focused on marketing, leads, and sales. The user selects their role during a mandatory onboarding process.

## Key Features

### Strategy & Automation
- **AI Content Strategist**: Users input their niche/business type, audience, and goals. The AI generates a multi-week content plan with topics and formats.
- **AI Autopilot (for Creators)** / **AI Marketing Manager (for Businesses)**: A premium add-on that automates entire campaigns. Users select a "Campaign Idea" (e.g., "Promote a new product") or write a custom goal. The AI then generates a full strategy and all the posts for approval.
- **Dynamic Campaign Ideas**: The suggestions in Autopilot are NOT static; they are dynamically generated by AI based on the user's specific profile (niche, audience, user type).

### Generative Content Suite
- **AI Image & Video Generation**: Creates unique images and high-quality video clips (using the Veo model) from text prompts.
- **AI Director Mode**: A multi-scene video editor for creating short films with consistent characters and styles.
- **AI Avatar**: Users on premium plans can upload a base image of themselves, which the AI uses as a reference to create new, consistent images of them.
- **Custom Voice Cloning**: Premium users can upload an audio sample to create an AI clone of their voice for generating video voice-overs.
- **"Spiciness" Slider**: An exclusive feature for Creators in Settings. It's a slider that allows them to control the level of "sexy/explicit" language in the AI's tone, from "Safe" to "Explicit". This is hidden for Business accounts.

### Inbox & CRM
- **AI-Powered Inbox**: Manages DMs and comments in one feed. The AI drafts replies in the user's voice for one-click approval.
- **Social CRM**: A sidebar that appears when a user is clicked in the inbox. It allows for adding internal notes, applying tags (e.g., 'Lead', 'VIP'), and viewing interaction history. The AI can also generate a summary of the relationship.

### Planning & Collaboration
- **Visual Content Calendar**: A drag-and-drop calendar for scheduling posts. It highlights "Best Time" posting slots recommended by the AI.
- **Approval Workflow**: A Kanban board for teams and agencies to move posts through 'Draft', 'In Review', and 'Approved' stages.
- **Team & Client Management**: Agency plans allow inviting team members and managing multiple client accounts from a single dashboard.

### Conversion Tools
- **Smart Link-in-Bio Builder**: A tool to create a mobile-optimized landing page for social profiles, which includes an email capture form.

## Pricing Plans & Tiers

The app has separate pricing for Creators and Businesses.

### Creator Plans
- **Free**: 1 social account, 50 AI replies/month, basic features.
- **Pro**: $49/mo. 3 social accounts, 500 replies, AI Content Strategist, 50 image/1 video generation.
- **Elite**: $199/mo. 5 social accounts, 1,500 replies, Advanced CRM, 500 image/25 video generations, 3 voice clones.

### Business Plans
- **Starter**: $99/mo. 3 social accounts, 1,000 AI replies, AI Marketing Manager, Business Analytics.
- **Growth**: $249/mo. 5 social accounts, 2,500 replies, Competitor Analysis, Social Listening.
- **Agency**: $599/mo. Unlimited accounts, unlimited replies, Client Workflows, Team Management.

## How-To Guides
- **How to connect an account?**: Go to Settings > Connections and click the "Connect" button for the desired social media platform.
- **How to create a campaign?**: Go to the "AI Autopilot" (or "AI Marketing Manager") page. Either select a dynamic, AI-generated "Campaign Idea" or type your own custom goal into the text box, then click "Launch Campaign".
- **How to restart onboarding?**: To test the different user experiences, go to Settings > Advanced and click the "Restart Onboarding" button. This will log you out and allow you to re-select your user type.
- **What if I run out of AI credits?**: On higher-tier plans (Elite/Agency), you can enable the "Bring Your Own Key" (BYOK) model. This allows you to connect your own Google AI API key, and all further usage is billed directly to your Google Cloud account at cost.
`;